### PR TITLE
⚡️ perf(ctx.Range): reduce allocations

### PR DESCRIPTION
**Pull request by nickajacks1**
## Description

`strings.Split` was causing extra allocations where `strings.Cut` can suffice. Also switch from `strconv.Atoi` because it causes an allocation when parsing a non-integer, which is common for Ranges.

The remaining allocation (see benchmarks) comes from the returned slice.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

## Bench:
```
                            │  master.txt  │             branch.txt              │
                            │    sec/op    │   sec/op     vs base                │
_Ctx_Range/bytes=-700-8       197.80n ± 0%   65.06n ± 0%  -67.11% (p=0.000 n=20)
_Ctx_Range/bytes=500--8       198.10n ± 0%   63.70n ± 0%  -67.84% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8   162.30n ± 0%   64.76n ± 0%  -60.10% (p=0.000 n=20)
_Ctx_Range/bytes=500-700-8    161.75n ± 0%   64.48n ± 0%  -60.14% (p=0.000 n=20)
geomean                        179.1n        64.50n       -63.98%

                            │ master.txt  │             branch.txt             │
                            │    B/op     │    B/op     vs base                │
_Ctx_Range/bytes=-700-8       144.00 ± 0%   16.00 ± 0%  -88.89% (p=0.000 n=20)
_Ctx_Range/bytes=500--8       144.00 ± 0%   16.00 ± 0%  -88.89% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8    96.00 ± 0%   16.00 ± 0%  -83.33% (p=0.000 n=20)
_Ctx_Range/bytes=500-700-8     96.00 ± 0%   16.00 ± 0%  -83.33% (p=0.000 n=20)
geomean                        117.6        16.00       -86.39%

                            │ master.txt │             branch.txt             │
                            │ allocs/op  │ allocs/op   vs base                │
_Ctx_Range/bytes=-700-8       5.000 ± 0%   1.000 ± 0%  -80.00% (p=0.000 n=20)
_Ctx_Range/bytes=500--8       5.000 ± 0%   1.000 ± 0%  -80.00% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8   4.000 ± 0%   1.000 ± 0%  -75.00% (p=0.000 n=20)
_Ctx_Range/bytes=500-700-8    4.000 ± 0%   1.000 ± 0%  -75.00% (p=0.000 n=20)
geomean                       4.472        1.000       -77.64%
```

### CODE REVIEW

**Comment by ReneWerner87** [comment]
thanks for the optimization

unfortunately we can't do it like this
because of
image
image

maybe you can do the exchange of the cut function only for the golang version from 1.18 ? here an example
https://github.com/gofiber/fiber/blob/master/utils/convert_s2b_new.go#L1
https://github.com/gofiber/fiber/blob/master/utils/convert_s2b_old.go#L1

**Comment by efectn** [comment]
> thanks for the optimization
> 
> unfortunately we can't do it like this because of image image
> 
> maybe you can do the exchange of the cut function only for the golang version from 1.18 ? here an example https://github.com/gofiber/fiber/blob/master/utils/convert_s2b_new.go#L1 https://github.com/gofiber/fiber/blob/master/utils/convert_s2b_old.go#L1

Or we can use strings.Index instead of strings.Cut. It might worth for performance gain on 1.17

**Comment by ReneWerner87** [comment]
ok sure, lets test this

**Comment by nickajacks1** [comment]
Sure, I'll try out strings.IndexByte

**Comment by gaby** [comment]
@nickajacks1 

```
Error: ./ctx.go:1398:26: undefined: strings.Cut
Error: ./ctx.go:1410:40: undefined: strings.Cut
note: module requires Go 1.20
```

**Comment by ReneWerner87** [comment]
@nickajacks1 any progress?

**Comment by nickajacks1** [comment]
Yes, sorry, been busy. Just need to find time to sit down and finish this.  Should be ready within the next couple days.

**Comment by nickajacks1** [comment]
Removed strings.Cut, added more tests, updated Benchmark to include a case with multiple ranges.
New benchmarks:
```
                                  │  master.txt  │             branch.txt              │
                                  │    sec/op    │   sec/op     vs base                │
_Ctx_Range/bytes=-700-8             198.20n ± 1%   55.46n ± 1%  -72.02% (p=0.000 n=20)
_Ctx_Range/bytes=500--8             197.50n ± 0%   55.08n ± 0%  -72.11% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8         160.60n ± 0%   55.93n ± 1%  -65.18% (p=0.000 n=20)
_Ctx_Range/bytes=0-700,800-1000-8   245.10n ± 0%   93.25n ± 0%  -61.95% (p=0.000 n=20)
geomean                              198.1n        63.18n       -68.11%

                                  │ master.txt  │             branch.txt             │
                                  │    B/op     │    B/op     vs base                │
_Ctx_Range/bytes=-700-8             144.00 ± 0%   16.00 ± 0%  -88.89% (p=0.000 n=20)
_Ctx_Range/bytes=500--8             144.00 ± 0%   16.00 ± 0%  -88.89% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8          96.00 ± 0%   16.00 ± 0%  -83.33% (p=0.000 n=20)
_Ctx_Range/bytes=0-700,800-1000-8   176.00 ± 0%   48.00 ± 0%  -72.73% (p=0.000 n=20)
geomean                              136.8        21.06       -84.61%

                                  │ master.txt │             branch.txt             │
                                  │ allocs/op  │ allocs/op   vs base                │
_Ctx_Range/bytes=-700-8             5.000 ± 0%   1.000 ± 0%  -80.00% (p=0.000 n=20)
_Ctx_Range/bytes=500--8             5.000 ± 0%   1.000 ± 0%  -80.00% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8         4.000 ± 0%   1.000 ± 0%  -75.00% (p=0.000 n=20)
_Ctx_Range/bytes=0-700,800-1000-8   6.000 ± 0%   2.000 ± 0%  -66.67% (p=0.000 n=20)
geomean                             4.949        1.189       -75.97%
```

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
