### PR TITLE
Adding new QueryParser

### PR DESCRIPTION
**Pull request by brunodmartins**
## Description

Adding a new generic function called `QueryParser` to parse a query value directly into a generic type. 

Related to #2758

## Changes Introduced

List the new features or adjustments introduced in this pull request. Provide details on benchmarks, documentation updates, changelog entries, and if applicable, the migration guide.

- [ ] Benchmarks: Describe any performance benchmarks and improvements related to the changes.
- [ ] Documentation Update: Detail the updates made to the documentation and links to the changed files.
- [ ] Changelog/What's New: Include a summary of the additions for the upcoming release notes.
- [ ] Migration Guide: If necessary, provide a guide or steps for users to migrate their existing code to accommodate these changes.
- [ ] API Alignment with Express: Explain how the changes align with the Express API.
- [ ] API Longevity: Discuss the steps taken to ensure that the new or updated APIs are consistent and not prone to breaking changes.
- [ ] Examples: Provide examples demonstrating the new features or changes in action.

## Type of Change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to existing features and functionality)
- [ ] Documentation update (changes to documentation)
- [ ] Performance improvement (non-breaking change which improves efficiency)
- [ ] Code consistency (non-breaking change which improves code reliability and robustness)

## Checklist

Before you submit your pull request, please make sure you meet these requirements:

- [ ] Followed the inspiration of the Express.js framework for new functionalities, making them similar in usage.
- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [ ] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [x] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [x] Ensured that new and existing unit tests pass locally with the changes.
- [ ] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.
- [x] Aimed for optimal performance with minimal allocations in the new code.
- [ ] Provided benchmarks for the new code to analyze and improve upon.

## Commit Formatting

Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.md#pull-requests-or-commits)

### CODE REVIEW

**Comment by gaby** [comment]
@brunodmartins Can you take a look at the CI failures, thanks!

**Comment by ReneWerner87** [comment]
> @brunodmartins Can you take a look at the CI failures, thanks!

maybe not necessary, currently I prefer the other pull request https://github.com/gofiber/fiber/pull/2776#pullrequestreview-1800442239

but anyway, thx for the effort

**Comment by gaby** [comment]
> > @brunodmartins Can you take a look at the CI failures, thanks!
> 
> maybe not necessary, currently I prefer the other pull request [#2776 (review)](https://github.com/gofiber/fiber/pull/2776#pullrequestreview-1800442239)
> 
> but anyway, thx for the effort

Can we close it then?

**Comment by brunodmartins** [comment]
Sure I will close it! Although, the tests on CI were failing due to a concurrency problem not related to the modified code!

**Pull request closed without merging**
