### PR TITLE
Add support for streaming the request body.

### PR DESCRIPTION
**Pull request by TroyDota**
Literally exposed 2 config options from fasthttp to allow for request body streaming. No breaking changes.

### CODE REVIEW

**Comment by TroyDota** [comment]
Currently I was maintaining a separate branch for my work since I needed http body streaming but since the change is so small I thought I would just PR it.

**Comment by sneakykiwi** [comment]
Could you show some example usage if possible?

**Comment by TroyDota** [comment]
Sure, we used it here to stream uploaded data.
https://github.com/SevenTV/ServerGo/blob/c9ade67744306e3944be3aecfa3a998aa8f7fc99/src/server/api/v2/rest/emotes/create-emote.go#L57

**Comment by ReneWerner87** [comment]
Thanks for the work, can you provide some unittests for it so that the feature still works as expected in the future(even if we adjust the code later)

And please another example of how to use it in the documentation.

**Comment by ReneWerner87** [comment]
@TroyDota

**Comment by TroyDota** [comment]
@ReneWerner87 Hi, Sure will do tonight just at work 👍

**Comment by ReneWerner87** [comment]
Thx

**Comment by TroyDota** [comment]
@ReneWerner87 Adding tests.

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@TroyDota okay now we just need a part in our documentation repository
https://github.com/gofiber/docs

**Comment by TroyDota** [comment]
@ReneWerner87 👍

**Pull request merged**
