### PR TITLE
🐛 Cache Middleware - Race condition in the cache expiration logic. Round 2

### PR DESCRIPTION
**Pull request by defshift**
After a not quite successful attempt to fix flaky tests for the cache middleware in #1229  I'd want to propose to get current timestamp every time when the middleware is executed, since it's the most stable way to expire cache in time.

Alternative way would be to not check the expiration at all and leave it up to caching the backend.

### CODE REVIEW

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
we had tested this performance boost and it has a very big impact, so building back would not be good

**Comment by defshift** [comment]
got it. Ok, let me think what we can do here

**Comment by defshift** [comment]
@ReneWerner87 Updated the PR. Decreased timestamp update period from 1s to 300ms. It should be enough to provide acceptable cache expiration error and it's not too overwhelming. What do you think?

Btw. Checked benchmarks. You'r right, the impact is significant.

**Review by ReneWerner87 — APPROVED** [review]
looks good

**Comment by ReneWerner87** [comment]
hopefully the problems will disappear, thought we had to adjust the test, but a third of the time for the loop is also okay

**Pull request merged**
