### PR TITLE
🔥Feature: add Match() function

### PR DESCRIPTION
**Pull request by KiddoV**
## Description
Match() function will help users to choose between adding one or more HTTP methods instead of just, currently, one or all method(s).

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by ReneWerner87** [comment]
thanks for the work
but i would not include this helper method in the core, because this is not necessary due to the method chaining and there are hardly any use cases for it

alternatively you can use the app.All method, if the handler should be registered everywhere

**Comment by KiddoV** [comment]
Correct me if I'm wrong, but I think this is necessary since in some cases, users only need to deal with, for example, 2 methods, say "GET" and "POST". So instead of bringing all with ``app.All()`` (could waste some memory for unnecessary methods), they have more option to choose.
Also, we can filter out the wrong method in the handler if the client try to request, for example, with "PUT" or something else.

Thanks,

**Comment by ReneWerner87** [comment]
yes right, but that is easily possible with 
```go
app.Get(path, handler).Post(path, handler)
```

**Comment by ReneWerner87** [comment]
we just have to make sure that the core is not too bloated with methods that are not for the majority, so i would decide against this helper method

in v3 you have the possibility to extend the context with your own methods so we can easily extend helper methods and have them in separate repositories

**Comment by efectn** [comment]
```go
app.route('/events')
  .all(function (req, res, next) {
    // runs for all HTTP verbs first
    // think of it as route specific middleware!
  })
  .get(function (req, res, next) {
    res.json({})
  })
  .post(function (req, res, next) {
    // maybe add a new event...
  })
```

Express has a method like this. We were planning to add something like this for v3

**Comment by KiddoV** [comment]
Sounds good. Thanks for the clarification!

**Pull request closed without merging**
