### PR TITLE
🔥Feature (v3): Add TrustInternalIPs Config Option

### LINKED ISSUE #2930: 📝 [Proposal]: Add Helpers for Internal IP Ranges
### Feature Proposal Description

Currently, adding loopback, link-local, and private network addresses to the `fiber.Config.TrustedProxies` list requires us to manually add those ranges. Since web apps are commonly deployed behind reverse proxies, it would be helpful to have a simple way of adding these ranges without needing to search them up.

When configuring trusted proxies in Echo framework, the setup is a bit different:
```go
e := echo.New()
_, myProxyRange, _ := net.ParseCIDR("173.245.48.0/20")
e.IPExtractor = echo.ExtractIPFromXFFHeader(
	echo.TrustLoopback(true), // e.g. ipv4 start with 127. 
	echo.TrustLinkLocal(true), // e.g. ipv4 start with 169.254
	echo.TrustPrivateNet(true), // e.g. ipv4 start with 10. or 192.168
	echo.TrustIPRange(myProxyRange),
)
```

In Fiber, an equivalent setup would look something like
```go
app := fiber.New(fiber.Config{
	ProxyHeader:             fiber.HeaderXForwardedFor,
	EnableTrustedProxyCheck: true,
	TrustedProxies: []string{
		"127.0.0.0/8",    // Loopback addresses
		"169.254.0.0/16", // Link-Local addresses
		"fe80::/10",
		"192.168.0.0/16", // Private Network addresses
		"172.16.0.0/12",
		"10.0.0.0/8",
		"fc00::/7",
		"173.245.48.0/20", // My custom range
	},
})
```

Although I prefer Fiber's method of using an array of strings, it would be nice to have constants like:
```go
// Fiber helpers.go
// Note: This is not an exhaustive list.
const (
        ...
	IPv4Loopback      = "127.0.0.0/8"
	IPv4LinkLocal     = "169.254.0.0/16"
	IPv4PrivateSmall  = "192.168.0.0/16"
	IPv4PrivateMedium = "172.16.0.0/12"
	IPv4PrivateLarge  = "10.0.0.0/8"
	IPv6Loopback      = "::1/128"
	IPv6LinkLocal     = "fe80::/10"
	IPv6PrivateNet    = "fc00::/7"
)
```

This would allow developers to use
```go
app := fiber.New(fiber.Config{
	ProxyHeader:             fiber.HeaderXForwardedFor,
	EnableTrustedProxyCheck: true,
	TrustedProxies: []string{
		fiber.IPv4Loopback,
		fiber.IPv4LinkLocal,
		fiber.IPv4PrivateSmall,
		fiber.IPv4PrivateMedium,
		fiber.IPv4PrivateLarge,
		fiber.IPv6Loopback,
		fiber.IPv6LinkLocal,
		fiber.IPv6PrivateNet,
		"173.245.48.0/20",  // My custom range
	},
})
```

They don't necessarily need to be constants. We could add a new config option to `fiber.Config` instead:
```go
app := fiber.New(fiber.Config{
	ProxyHeader:             fiber.HeaderXForwardedFor,
	EnableTrustedProxyCheck: true,
	TrustInternalIPs: true, // default to false
	TrustedProxies: []string{
		"173.245.48.0/20",  // My custom range
	},
})
```
This would be far easier, but at the cost of allowing developers to cherry pick individual ranges. Those cases are probably rare though, which might be why Echo's helper functions for these ranges [default to true](https://github.com/labstack/echo/blob/d549290448fc65ae075f0b960b25489f6a38cb78/ip.go#L154).

### Alignment with Express API

Express.js allows developers to [set trusted proxy settings using pre-defined subnets](https://expressjs.com/en/5x/api.html#trust.proxy.options.table):
```js
// loopback - 127.0.0.1/8, ::1/128
// linklocal - 169.254.0.0/16, fe80::/10
// uniquelocal - 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
app.set('trust proxy', ['loopback', 'linklocal', 'uniquelocal']) 
```

### HTTP RFC Standards Compliance

n/a (this is a quality of life improvement)

### API Stability

IP address ranges don't change.

### Feature Examples

```go
(Listed above)
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

### PR DESCRIPTION
**Pull request by xEricL**
# Description

This adds a new config option called `TrustInternalIPs`, allowing developers to trust Loop-back, Private, and Link-local IP addresses without adding the ranges to `TrustedProxies` when `EnableTrustedProxyCheck` is enabled. If these ranges are added manually, it can negatively impact performance (see #2933 benchmarks).

I chose these three ranges because these are the same ranges enabled by default when configuring an [IP extractor in Echo](https://github.com/labstack/echo/blob/d20a6257aa1263681e2ce1f020f8d801a8be9782/ip.go#L174).

Fixes #2930

## Changes introduced

- [x] Benchmarks: Describe any performance benchmarks and improvements related to the changes.
- [x] Documentation Update: Detail the updates made to the documentation and links to the changed files.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement (improvement to existing features and functionality)
- [x] Documentation update (changes to documentation)
- [x] Performance improvement (non-breaking change which improves efficiency)

## Checklist

Before you submit your pull request, please make sure you meet these requirements:

- [x] Followed the inspiration of the Express.js framework for new functionalities, making them similar in usage.
- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [x] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [x] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [x] Ensured that new and existing unit tests pass locally with the changes.
- [x] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.
- [x] Aimed for optimal performance with minimal allocations in the new code.
- [x] Provided benchmarks for the new code to analyze and improve upon.

## Commit formatting

Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.md#pull-requests-or-commits)

### CODE REVIEW

**Comment by gaby** [comment]
Per discord conversation something like this will be added to make this more user-friendly:

```go
type TrustedProxyConfig struct {
    IPs                []string
    Ranges             []string
    Unicast            bool
    Multicast          bool
    LinkLocalUnicast   bool
    LinkLocalMulticast bool
    Loopback           bool
    Private            bool
}
```

**Comment by ReneWerner87** [comment]
@xEricL thx for the PR
Can you implement the suggested changes from gaby

**Comment by gaby** [comment]
@ReneWerner87 I talked to @xEricL on Discord, he will be implemented the options from Express.js

https://expressjs.com/en/guide/behind-proxies.html

**Comment by ReneWerner87** [comment]
@gaby @xEricL friendly ping

**Comment by xEricL** [comment]
@ReneWerner87 hey, I'm sorry I've been very busy with school so I haven't had a chance to finish it up. I've had it mostly done for a while now but I'm having second thoughts about how it looks; It just feels a bit verbose.

Here are some examples. What do you guys think?

```go
app := fiber.New(fiber.Config{
        EnableTrustedProxyCheck: true,
        TrustedProxyConfig: fiber.TrustedProxyConfig{
            Proxies: []string{"192.168.0.0/24", "10.0.0.0/16", "0.0.0.0/8"},
        },
    })
```
```go
app := New(Config{
	EnableTrustedProxyCheck: true,
	TrustedProxyConfig: fiber.TrustedProxyConfig{
		Proxies: []string{"172.16.0.0/12"},
		Loopback: true,
	},
})
```

**Comment by gaby** [comment]
@xEricL In express.js this is actually called "trust proxy". See here https://expressjs.com/en/guide/behind-proxies.html

How about this? 

```go
app := New(Config{
	TrustProxy: true,
	TrustProxyConfig: fiber.TrustProxyConfig{
		Proxies: []string{"172.16.0.0/12"},
		Loopback: true,
	},
})
```

@ReneWerner87 @efectn Thoughts?

**Comment by efectn** [comment]
> @xEricL In express.js this is actually called "trust proxy". See here [expressjs.com/en/guide/behind-proxies.html](https://expressjs.com/en/guide/behind-proxies.html)
> 
> How about this?
> 
> ```go
> app := New(Config{
> 	TrustProxy: true,
> 	TrustProxyConfig: fiber.TrustProxyConfig{
> 		Proxies: []string{"172.16.0.0/12"},
> 		Loopback: true,
> 	},
> })
> ```
> 
> @ReneWerner87 @efectn Thoughts?

It seems OK to me.

**Comment by xEricL** [comment]
I've opened a new PR with a new implementation for this feature. https://github.com/gofiber/fiber/pull/3170

**Pull request closed without merging**
