### PR TITLE
📺 Added new video

### PR DESCRIPTION
**Pull request by EQuimper**

### CODE REVIEW

**Comment by Fenny** [comment]
Hi @EQuimper, could you add the 📺 emoji in front of your commit? Thank you ❤️

**Comment by EQuimper** [comment]
@Fenny o you did merge before I push the change :) Thank you :)

**Comment by Fenny** [comment]
I had to add the new links to all translations anyway 😄 <https://github.com/gofiber/fiber/pull/687>

**Comment by EQuimper** [comment]
@Fenny perfect and thank you for fiber :) I'm working on a pretty big series with it on my youtube channel. Really love the docs etc :) Great job

**Pull request merged**
