### PR TITLE
:sparkles: feat: add strings reverse and strings contain func in utils.strings file

### PR DESCRIPTION
**Pull request by ShyunnY**
## Description

This pr adds two commonly used string functions. I believe that in many cases string reversal and the function of determining whether the string is in the specified slice will be used. Therefore, I write this pr.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by ReneWerner87** [comment]
please also add the internal usage, otherwise we would have to move the whole thing to the utils package
https://github.com/gofiber/utils

**Comment by ShyunnY** [comment]
> please also add the internal usage, otherwise we would have to move the whole thing to the utils package https://github.com/gofiber/utils

There may be codes similar to these two functions inside the fiber, but I haven't found it yet. But when writing logic/service. These two functions are used more often. @ReneWerner87

**Comment by gaby** [comment]
I feel like this should go in `gofiber/utils/v2`

**Comment by ShyunnY** [comment]
> I feel like this should go in `gofiber/utils/v2`



> I feel like this should go in `gofiber/utils/v2`

I do not understand. I can only see `gofiber/utils`. `gofiber/utils/v2` was not found. So should my current PR be resubmitted into `gofiber/utils`?

**Comment by gaby** [comment]
> > I feel like this should go in `gofiber/utils/v2`
> 
> I do not understand. I can only see `gofiber/utils`. `gofiber/utils/v2` was not found. So should my current PR be resubmitted into `gofiber/utils`?

It's the v2 branch under https://github.com/gofiber/utils

**Comment by leonklingele** [comment]
Why do we need this as part of fiber? I wouldn’t add code which is not used at all.

**Comment by gaby** [comment]
@ReneWerner87 Do we move this to utils repo, or close it?

**Pull request closed without merging**
