### PR TITLE
🚀 Feature: Add idempotency middleware (v2 backport)

### PR DESCRIPTION
**Pull request by leonklingele**
## Description

Add idempotency middleware.
Implements https://github.com/gofiber/fiber/issues/2163.

This is a v2 backport of https://github.com/gofiber/fiber/pull/2253.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

### CODE REVIEW

**Comment by leonklingele** [comment]
CI is failing for some unrelated data race.

**Review by efectn — APPROVED** [review]
OK to me after creating a PR for docs repo

**Comment by leonklingele** [comment]
@efectn why is this even required? It's a 1:1 copy of the README here, why can't this be automated as follows?

```sh
# From inside the docs repo:
git clone --depth 1 https://github.com/gofiber/fiber
find fiber/middleware -maxdepth 2 -name 'README.md' -exec bash -c 'MW="$(basename $(dirname {}))" ; cp "{}" "api/middleware/$MW.md"' \;
rm -rf fiber
```

**Comment by ReneWerner87** [comment]
i will create the docs PR, shortly before the release

**Comment by leonklingele** [comment]
Nice! I noticed that the docs in this repo slightly differ from the ones in the `docs` repo. Can you make sure they are a identical copy? Simply use the commands from above.. Thank you! 😊

**Comment by ReneWerner87** [comment]
I think there is a reason for this :D

**Comment by leonklingele** [comment]
> I think there is a reason for this :D

The doc repo for example uses space-indentation for code while this repo uses tabs. There should not be a reason for that ;)

> Later, when we are on docusaurus, by the way, the idea is to To remove the doc repository and maintain and use all the documentation in the core repository.

That would be awesome! 🚀

**Pull request merged**
