### PR TITLE
chore: replace vendored gorilla/schema package

### PR DESCRIPTION
**Pull request by efectn**
# Description

Replace internal/schema with https://github.com/gofiber/schema which is fork of gorilla/schema.

- Also closes https://github.com/gofiber/fiber/pull/2699 as gorilla recently added default tag support.

## Changes introduced
- [x] Benchmarks: Describe any performance benchmarks and improvements related to the changes.
- [x] Documentation Update: Detail the updates made to the documentation and links to the changed files.
- [ ] Changelog/What's New: Include a summary of the additions for the upcoming release notes.
- [ ] Migration Guide: If necessary, provide a guide or steps for users to migrate their existing code to accommodate these changes.
- [x] API Alignment with Express: Explain how the changes align with the Express API.
- [x] API Longevity: Discuss the steps taken to ensure that the new or updated APIs are consistent and not prone to breaking changes.
- [x] Examples: Provide examples demonstrating the new features or changes in action.

## Type of change
- [x] Enhancement (improvement to existing features and functionality)

## Checklist

Before you submit your pull request, please make sure you meet these requirements:

- [ ] Followed the inspiration of the Express.js framework for new functionalities, making them similar in usage.
- [ ] Conducted a self-review of the code and provided comments for complex or critical parts.
- [ ] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [ ] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [ ] Ensured that new and existing unit tests pass locally with the changes.
- [ ] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.
- [ ] Aimed for optimal performance with minimal allocations in the new code.
- [ ] Provided benchmarks for the new code to analyze and improve upon.

## Commit formatting

Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.md#pull-requests-or-commits)

### CODE REVIEW

**Comment by gaby** [comment]
@efectn Did you add the changes we had here to gofiber/schema?

**Comment by efectn** [comment]
> @efectn Did you add the changes we had here to gofiber/schema?

Yes i've added

**Comment by ReneWerner87** [comment]
@efectn can you check the failed and open tasks
thx for the effort 🚀

**Comment by efectn** [comment]
> @efectn can you check the failed and open tasks thx for the effort 🚀

Done

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@efectn @gaby should i make a release for schema repo first ?

**Comment by efectn** [comment]
> @efectn @gaby should i make a release for schema repo first ?

Sure, we can

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/schema/releases/tag/v1.0.0

@efectn can you update

**Review by gaby — APPROVED** [review]
👍 LGTM

**Pull request merged**
