### PR TITLE
Update cookie.go

### PR DESCRIPTION
**Pull request by Hasan-Kilici**
## Description
although the performance difference is not much, there is a possibility that it will run 2-4ms faster this way

### CODE REVIEW

**Review by cmd777 — CHANGES_REQUESTED** [review]
This is the v3 branch

**Review by efectn — COMMENTED** [review]
Can you explain why this change is needed

**Comment by ReneWerner87** [comment]
@Hasan-Kilici friendly ping

**Comment by leonklingele** [comment]
Any benchmarks on this? I doubt it will actually improve performance.

**Pull request closed without merging**
