### PR TITLE
Fix `route.Path` on copy

### PR DESCRIPTION
**Pull request by ProExpertProg**
**Please provide enough information so that others can review your pull request:**

Fixed route path copying in `app.copyRoute`.

**Explain the *details* for making this change. What existing problem does the pull request solve?**

Fixed issue in #1470.

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

Was gonna do that on squash & merge

### CODE REVIEW

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
Thx

**Comment by ProExpertProg** [comment]
@ReneWerner87 can someone squash and merge this?

**Comment by ReneWerner87** [comment]
Its merged

**Comment by ProExpertProg** [comment]
Great, thanks!

**Pull request merged**
