### PR TITLE
:sparkles: Feature: add ShutdownWithContext

### PR DESCRIPTION
**Pull request by li-jin-gou**
## Description

add ShutdownWithContext

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I tried to make my code as fast as possible with as few allocations as possible

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by ReneWerner87** [comment]
thanks for the feature
please remember the checkpoints and remove everything that does not apply and check off everything already done

**Comment by li-jin-gou** [comment]
> thanks for the feature please remember the checkpoints and remove everything that does not apply and check off everything already done

OK，thanks

**Comment by pjebs** [comment]
This doesn't address #2087 at all. Perhaps my feature request was misunderstood.

**Comment by li-jin-gou** [comment]
> This doesn't address #2087 at all. Perhaps my feature request was misunderstood.
> 
> It needs to force the shutdown.

sorry,

> This doesn't address #2087 at all. Perhaps my feature request was misunderstood.
> 
> It needs to force the shutdown.

Sorry, maybe I misunderstood it

**Comment by efectn** [comment]
I think **context with timeout** would be good idea for force shutdown. Fasthttp waits closing of connections. So this should be the best solution.

**Comment by pjebs** [comment]
There needs to be a way force the shutdown (ungracefully), if it can't be shutdown gracefully within a certain time limit.

**Comment by efectn** [comment]
> There needs to be a way force the shutdown (ungracefully), if it can't be shutdown gracefully within a certain time limit.

Why dont you use `os.Exit()`

**Comment by li-jin-gou** [comment]
Is this pr still needed? :roll_eyes:

**Comment by pjebs** [comment]
No

**Pull request closed without merging**
