### PR TITLE
:adhesive_bandage: Fix: Properly handle error of "net.ParseCIDR" in "(*App).handleTrustedProxy"

### PR DESCRIPTION
**Pull request by leonklingele**
## Description

- Do not use empty `*net.IPNet` in case of an error of `net.ParseCIDR`
- Add test for `ctx.IsProxyTrusted()`
- Optimize `ctx.IsProxyTrusted()` by caching method call

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

### CODE REVIEW

**Comment by leonklingele** [comment]
See the individual commits for details.

**Review by li-jin-gou — CHANGES_REQUESTED** [review]
I noticed that the title and description of your pr are not the same as most PRs. and you should refer to https://github.com/gofiber/fiber/pull/2152 or https://github.com/gofiber/fiber/pull/2188 etc.. and modify the title and description of the PR according to the pull request template.

**Review by efectn — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@leonklingele can you please add one more test case for this kind of behavior
 and next time follow the pull request template form where you work through the checklist

**Comment by leonklingele** [comment]
Updated, ptal.

**Review by ReneWerner87 — APPROVED** [review]

**Review by li-jin-gou — APPROVED** [review]

**Pull request merged**
