### PR TITLE
✨ Add fiber-inertia to README.md

### PR DESCRIPTION
**Pull request by theArtechnology**
It is an inertia.js server-side adapter which helps creating single-page apps without building an API, using classic server-side routing and controllers.

### CODE REVIEW

**Comment by kiyonlin** [comment]
Could you add it to other language reamdes?

**Comment by theArtechnology** [comment]
> Could you add it to other language reamdes?

Yes

**Comment by theArtechnology** [comment]
There you go !

**Review by kiyonlin — APPROVED** [review]
Thanks a lot!

**Pull request merged**
