### PR TITLE
Use regexp to find next segment end

### PR DESCRIPTION
**Pull request by larrylv**
**Please provide enough information so that others can review your pull request:**

This PR changes the implementation of `findNextRouteSegmentEnd` from iterating the delimiters and find their first index, to using regexp to find the first match of either `/`, `-`, or `.`. Existing tests should cover testing this change.

I also plan to add `(` and `)` support in the route path in the next couple of days.

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by kiyonlin** [comment]
Thanks for your contribution! Could you please provide benchmark? We are sensitive to performance.

**Comment by ReneWerner87** [comment]
thanks for your effort

we have tried in version 1.9.6 to avoid regex usage for parsing and registering the route, because regex is much slower when analyzing the strings

please create a benchmark, if it is faster than the pre-behavior we will merge it but if it is slower we will not adopt it

https://github.com/gofiber/fiber/releases/tag/v1.9.6
> Improved router by ditching regexp and increased performance by 817% without allocations.

**Comment by larrylv** [comment]
@kiyonlin @ReneWerner87 thanks for the quick feedback. yeah, this is definitely slower than the `for` + `strings.IndexByte` implementation. I'll keep running benchmark in mind before opening next PR.

**Comment by ReneWerner87** [comment]
thanks anyway for trying to bring the fiber framework forward

**Pull request closed without merging**
