### PR TITLE
chore: Fix testifylint errors in middleware

### PR DESCRIPTION
**Pull request by nickajacks1**
## Description

Update various assertions in the middleware packages to match testify best practices in preparation for an upcoming update to golangci-lint. For float comparisons, an epsilon of 0.1% was chosen somewhat arbitrarily.

https://github.com/Antonboom/testifylint

## Type of Change

- [x] Code consistency (non-breaking change which improves code reliability and robustness)

## Checklist

- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [x] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [x] Ensured that new and existing unit tests pass locally with the changes.
- [x] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.

### CODE REVIEW

**Review by gaby — APPROVED** [review]
Lgtm

**Review by ReneWerner87 — APPROVED** [review]
Thx

**Comment by efectn** [comment]
We should enable testifylint on golangci-lint https://github.com/golangci/golangci-lint/pull/4103

**Comment by gaby** [comment]
> We should enable testifylint on golangci-lint [golangci/golangci-lint#4103](https://github.com/golangci/golangci-lint/pull/4103)

It requires updating golanci-lint first. But yes, makes sense

**Pull request merged**
