### PR TITLE
add NeedCache to control cache behavior

### PR DESCRIPTION
**Pull request by tianjipeng**
**Please provide enough information so that others can review your pull request:**
The intention of this PR is to address the issue raised here: [1116](https://github.com/gofiber/fiber/issues/1116)
It allows for configuration of controlling whether to cache or not

**Explain the *details* for making this change. What existing problem does the pull request solve?**
Provide NeedCache function to control whether to cache

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by kiyonlin** [comment]
There's no need to add an extra option to solve that issue. The `Next` option is enough, but it is in the wrong place. Cache middleware is a post-run handler, so we do cache stuff after `Ctx.Next`, so should `config.Next`.

**Comment by tianjipeng** [comment]
Cache Middleware has two part: get stuff from cache and put stuff to cache, ``config.Next`` now can only control both or not. So I think adding a ``NeedCache`` is reasonable to control whether to cache the response stuff. Do I understand it wrong?

**Comment by kiyonlin** [comment]
What do you think is the meaning of config.Next?

**Comment by tianjipeng** [comment]
I know the meaning of ``config.Next``.  But cache middleware is not only a post-run handler (put stuff to cache) but also a pre-run handler(get stuff from cache). I can't figure out how to implement the feature by ``config.Next``.  Could you give me some hint?

**Comment by kiyonlin** [comment]
Only if response is cached(post run), then pre run handler will be hit, right? So if you don't want a cached response(in pre run), you shouldn't cache it. Do I make it clear?

**Comment by tianjipeng** [comment]
Oh, I got it. Just put ``config.Next`` after ``ctx.Next``:
```go

if err := c.Next(); err != nil {
	return err
}

// Don't execute middleware if Next returns true
if cfg.Next != nil && cfg.Next(c) {
	return nil
}
```
Is tha right? If true, I will close this pr and reopen one.

**Comment by kiyonlin** [comment]
Yes, that is what I mean. When you make another pull request, could you please add some related test cases?

**Comment by tianjipeng** [comment]
ok, I will do that.

**Pull request closed without merging**
