### PR TITLE
Fix and optimize memory storage

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by leonklingele** [comment]
See the individual commits for details.

**Comment by leonklingele** [comment]
Why is there a similar memory storage available here: https://github.com/gofiber/fiber/tree/e388e0edb3c6d4bdbfa41e8d533e1f4bd734404d/internal/storage/memory ?

**Comment by ReneWerner87** [comment]
One is for testing the storage package

Check the first comment line in the file

**Comment by ReneWerner87** [comment]
@leonklingele can you pls apply this changes to the internal sorage/memory test adapter and later to https://github.com/gofiber/storage/blob/main/memory/memory.go#L116

**Comment by leonklingele** [comment]
@ReneWerner87 done.

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
