### PR TITLE
Add test case for QueryParser for SetParserDecoder

### PR DESCRIPTION
**Pull request by rockcreation7**
**Please provide enough information so that others can review your pull request:**

Adding Test case for QueryParser With SetParserDecoder for new possibility 

**Explain the *details* for making this change. What existing problem does the pull request solve?**

Continue on - https://github.com/gofiber/fiber/pull/1555
  
**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by ReneWerner87** [comment]
image

**Comment by ReneWerner87** [comment]
@rockcreation7 please check the unittests -> maybe both tests influence each other, you should reset the adjustments after the test again

**Comment by rockcreation7** [comment]
Thanks, let me check

**Comment by rockcreation7** [comment]
will update

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
