### PR TITLE
feat: add definition for overridable json engine

### PR DESCRIPTION
**Pull request by yquansah**
**Please provide enough information so that others can review your pull request:**
The intention of this PR is to address the issue raised here: https://github.com/gofiber/fiber/issues/1108

It allows for configuration of the underlying JSON marshaller/unmarshaller by clients of fiber. It will just default to the `encoding/json` implementation if one isn't provided a client.

**Explain the *details* for making this change. What existing problem does the pull request solve?**

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by yquansah** [comment]
Would appreciate suggestions on naming throughout this PR. Any and all feedback is more than welcomed.

**Comment by Fenny** [comment]
Thanks for the PR, `JSONEncoder` would be better. What ya think @kiyonlin @ReneWerner87 @hi019 @yquansah

**Review by renanbastos93 — APPROVED** [review]
LGTM

**Comment by yquansah** [comment]
@Fenny I agree. I can make that change 👍

**Comment by Fenny** [comment]
@yquansah, I do agree that your solution is more fitting for a more flexible approach if we add a json decoder in the future. But I highly doubt we will add that because we think that is not the responsibility of a web framework.

I still suggest simplifying it by using the STD json marshal signatures ( and add support for `Unmarshal` for BodyParser )

```go
JSONMarshal func(interface{}) ([]byte, error)
JSONUnmarshal func([]byte, interface{}) error
```

**Comment by yquansah** [comment]
@Fenny Yeah I was thinking about that too, I do not think there will be a use case of doing json decoding, and if there is then it shouldn't be too hard to add. Let me know if my changes address what you are talking about.

**Review by ReneWerner87 — APPROVED** [review]

**Comment by yquansah** [comment]
@ReneWerner87 @Fenny Hey y'all just wanted to check in and see if there is anything left to do on this PR?

**Review by ReneWerner87 — APPROVED** [review]
code looks good

can you add some words in 
https://github.com/gofiber/docs/blob/master/api/fiber.md
-> PR in the docs repository

**Comment by Fenny** [comment]
LGTM! Thanks!

**Pull request merged**
