### PR TITLE
:rocket: Consistent way of logging and fix middleware log format

### LINKED ISSUE #2402: 🚀 [Feature]: Consistent way of issuing fiber log messages / warnings / errors
### Feature Description

Currently, some fiber warnings & errors are done using `fmt.Print*`, some using `log.Print*`:

Examples:
- https://github.com/gofiber/fiber/blob/5a8bc44a1f55149d2f6b78ad128cb1d9c4c1c761/internal/template/html/html.go#L115
- https://github.com/gofiber/fiber/blob/5a8bc44a1f55149d2f6b78ad128cb1d9c4c1c761/app.go#L524

There should only be a single way of doing this.

### Additional Context (optional)

_No response_

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

### PR DESCRIPTION
**Pull request by kousikmitra**
## Description

- [x] Replace all fmt.Print* with log.Print*
- [x] Use `[MIDDLEWARENAME] - [LOG-LEVEL] text` in all middleware for logging

Fixes #2402 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by efectn** [comment]
We should add interface like https://github.com/labstack/echo/blob/master/log.go#L11 to make it customizable (maybe smaller). For example i may want to use zerolog, zap with fiber

**Comment by efectn** [comment]
> > We should add interface like https://github.com/labstack/echo/blob/master/log.go#L11 to make it customizable (maybe smaller). For example i may want to use zerolog, zap with fiber
> 
> That would be a good addition. I can work on it. But I think a separate PR would be better instead of adding here.

Ok to me

**Comment by leonklingele** [comment]
I'd prefer `[LEVEL] [SCOPE, e.g. MIDDLEWARE_NAME]` over the other way around.

Why don't we use a proper logging library like zerolog or zap though?

**Comment by efectn** [comment]
> I'd prefer `[LEVEL] [SCOPE, e.g. MIDDLEWARE_NAME] [MESSAGE] [DETAILS]` over having `[SCOPE] [LEVEL] ..`.
> 
> Why don't we use a proper logging library like zerolog or zap though?

We shouldn't add extra dependencies for optional things

**Comment by kousikmitra** [comment]
Totally agree with @efectn , I have opened an issue to track this. Please feel free to add additional context.

**Comment by gaby** [comment]
I agree with @leonklingele it should be `[LEVEL] [MIDDLEWARE_NAME] [MESSAGE]`. It looks weird to have the level after the middleware name

**Comment by leonklingele** [comment]
ftr: this‘ll soon be part of the Go stdlib 🫨🥳🚀

https://pkg.go.dev/golang.org/x/exp/slog

**Comment by efectn** [comment]
> ftr: this‘ll soon be part of the Go stdlib 🫨🥳🚀
> 
> https://pkg.go.dev/golang.org/x/exp/slog

Seems slower than zerolog and zap. At least for now https://github.com/uber-go/zap#performance

**Comment by kousikmitra** [comment]
> I agree with @leonklingele it should be `[LEVEL] [MIDDLEWARE_NAME] [MESSAGE]`. It looks weird to have the level after the middleware name

Ya agree, if others agree I will make the change here.

**Comment by leonklingele** [comment]
Why did this get merged already? Didn’t we want to change the order of log level and scope info?

**Comment by ReneWerner87** [comment]
Missed it, will revert it

next time it is better to store a task in the pull request or to reject it first, then I usually check it first 
but without this it is quite hard for me to keep track of the 10 repositories with all the communication in the pull requests and issues

**Comment by leonklingele** [comment]
I‘d leave it as-is and just do a fixup.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/2444

**Comment by ReneWerner87** [comment]
> We should add interface like https://github.com/labstack/echo/blob/master/log.go#L11 to make it customizable (maybe smaller). For example i may want to use zerolog, zap with fiber

what do you think about this kind of solution

```go
package main

import (
	"fmt"
	"log"
)

type Logger struct {
	topic string
}

func NewLogger(topic string) *Logger {
	return &Logger{topic: topic}
}

func (l *Logger) formatMessage(level, format string, args ...interface{}) string {
	message := fmt.Sprintf(format, args...)
	if l.topic != "" {
		return fmt.Sprintf("[%s] - [%s] %s", level, l.topic, message)
	}
	return fmt.Sprintf("[%s] - %s", level, message)
}

func (l *Logger) Info(format string, args ...interface{}) {
	log.Println(l.formatMessage("Info", format, args...))
}

func (l *Logger) Warning(format string, args ...interface{}) {
	log.Println(l.formatMessage("Warning", format, args...))
}

func (l *Logger) Error(format string, args ...interface{}) {
	log.Println(l.formatMessage("Error", format, args...))
}

func main() {
	cacheLogger := NewLogger("CACHE")
	cacheLogger.Warning("Key is deprecated, please use KeyGenerator")

	corsLogger := NewLogger("CORS")
	corsLogger.Warning("Both 'AllowOrigins' and 'AllowOriginsFunc' have been defined.")

	csrfLogger := NewLogger("CSRF")
	csrfLogger.Warning("TokenLookup is deprecated, please use KeyLookup")

	idempotencyLogger := NewLogger("IDEMPOTENCY")
	key := "example_key"
	err := fmt.Errorf("an error occurred")
	idempotencyLogger.Error("failed to unlock key %q: %v", key, err)

	generalLogger := NewLogger("")
	generalLogger.Warning("Parse() is deprecated, please use Load() instead.")
}
```

or we use the slog lib
https://pkg.go.dev/golang.org/x/exp/slog
the idea was from @leonklingele

**Pull request merged**
