### PR TITLE
🐛 fix: actual error not forwarded if request is not timed out.

### LINKED ISSUE #1496: 🐛 Timeout middleware is ignoring errors returned by the handler
**Fiber version**

**Issue description**

**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/timeout"
	"time"
)

func main() {
	app := fiber.New()

	// Steps to reproduce
	app.Get("/", timeout.New(func(c *fiber.Ctx) error {
		return fiber.NewError(fiber.StatusServiceUnavailable, "On vacation!")
	}, 1 * time.Minute))

	app.Listen(":3000")
}
```

The timeout middleware for timeout has this code snippet, and as shown it is ignoring errors returned by the handler
```
// logic is from fasthttp.TimeoutWithCodeHandler https://github.com/valyala/fasthttp/blob/master/server.go#L418
	return func(ctx *fiber.Ctx) error {
		ch := make(chan struct{}, 1)

		go func() {
			defer func() {
				_ = recover()
			}()
			_ = handler(ctx) /// <- Error being ignored
			ch <- struct{}{}
		}()

		select {
		case <-ch:
		case <-time.After(timeout):
			return fiber.ErrRequestTimeout
		}

		return nil
	}
```

### PR DESCRIPTION
**Pull request by akshaybharambe14**
Forwarded the actual error if request succeeds/fails in given timeout window.

fixes #1496

### CODE REVIEW

**Comment by ReneWerner87** [comment]
@akshaybharambe14 can you provide a test for this customization so we can make sure the workflow works as intended?

**Comment by akshaybharambe14** [comment]
I checked existing tests and all were commented out. Anyways, I will add tests.

**Comment by ReneWerner87** [comment]
ok thx
you can also try to reactivate the tests, I think someone had deactivated them because of the stability, we would have to try to get them back, best as stable as possible

**Comment by akshaybharambe14** [comment]
Yup, I will work on that this weekend.

**Comment by akshaybharambe14** [comment]
@ReneWerner87, is there any way to copy ctx?

Seems like, we need to copy Ctx fields.

**Comment by ReneWerner87** [comment]
> @ReneWerner87, is there any way to copy ctx?
> 
> Seems like, we need to copy Ctx fields.
@akshaybharambe14 
not really, but you are welcome to provide a function that can do that, I think something like that would be helpful

**Comment by ReneWerner87** [comment]
@akshaybharambe14

**Comment by ReneWerner87** [comment]
@akshaybharambe14 do you have time to look at the problem again?

**Comment by kevin-you2** [comment]
When will this issue be resolved and released?

**Pull request closed without merging**
