### PR TITLE
✨feature: print all routes message when server starts

### LINKED ISSUE #1675: 🚀 List all routes when server starts
**Is your feature request related to a problem?**
Is there any way to list all routes when server starts, like this:
image
**Describe the solution you'd like**
**Describe alternatives you've considered**
**Additional context**
I think it is useful and maybe I can give a pull request for it if maintainers agree.

### PR DESCRIPTION
**Pull request by vecpeng**
Closes #1675 
It will print something like this:
image

### CODE REVIEW

**Comment by efectn** [comment]
I think you can add "-"s after the table head. It would be great

**Review by ReneWerner87 — APPROVED** [review]

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
Please add the isChild check for our prefork mode
https://github.com/gofiber/fiber/blob/master/app.go#L1001

**Comment by ReneWerner87** [comment]
Please add a part for the doc repository https://github.com/gofiber/docs/blob/master/api/fiber.md#config

**Comment by vecpeng** [comment]
Ok，I will fix them tomorrow.

**Comment by vecpeng** [comment]
Thanks for your review. I finish them @ReneWerner87

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/1677#discussion_r776411396

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
