### PR TITLE
Fix: App Error Handler.

### PR DESCRIPTION
**Pull request by melbahja**
**Please provide enough information so that others can review your pull request:**
Fix to allow app `ErrorHandler` to handle 404 errors.

**Explain the *details* for making this change. What existing problem does the pull request solve?**
App config `ErrorHandler` not working with 404 errors.

### CODE REVIEW

**Comment by codemicro** [comment]
Hi @melbahja, thanks for the PR!

**Unfortunately, this PR is not going to be merged.** This change would be a breaking change that changes fundamental behaviour of the error handler in Fiber, which is also intended behaviour.

The pre-existing error handling logic in Fiber is designed to deal with errors that are returned by a handler somewhere in the stack of middlewares and handlers. It is not suitable for handling errors that have been caused by an invalid request (for example, a 404) as the error handler for these errors returns a HTTP 500 responses by default, which is the incorrect response code.

If you need to setup a custom 404 handler, you can find information on how to do this here, in our docs: https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses

**Comment by kiyonlin** [comment]
> If you need to setup a custom 404 handler, you can find information on how to do this here, in our docs: https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses

Beside @codemicro mentioned above, you can also write your own `ErrorHandler` to handle all kinds of errors.

**Comment by melbahja** [comment]
On line 137 if we return `app.Error` instead that, this will fix the tests!
```go
// this
err := Error{Code: StatusNotFound, Message: fmt.Sprintf("Cannot %s %s", c.method, c.pathOriginal)}

// instead of
err = fmt.Errorf("Cannot %s %s", c.method, c.pathOriginal)
```
 I was gonna pass the tests, but you closed the PR quickly.

**Comment by kiyonlin** [comment]
Hey @melbahja , what does `App config ErrorHandler not working with 404 errors.` mean exactly? Do you have any examples?

**Comment by melbahja** [comment]
@kinbiko 

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {

	app := fiber.New(fiber.Config{
		// Override default error handler
		ErrorHandler: func(ctx *fiber.Ctx, err error) error {
			// Statuscode defaults to 500
			code := fiber.StatusInternalServerError

			// Retreive the custom statuscode if it's an fiber.*Error
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}

			// Send custom error page
			return ctx.Status(code).SendString("My ErrorHandler Message")
		},
	})

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	app.Listen(":3000")

}
```

```bash
$ curl -i http://localhost:3000/not_found

HTTP/1.1 404 Not Found
Date: Thu, 26 Nov 2020 15:10:49 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21

Cannot GET /not_found
```
Expecting: `My ErrorHandler Message`

**Comment by kiyonlin** [comment]
I think you misunderstood what `ErrorHandler` does. In your example, no error happens. It's correct to return 404 because you don't have a route with path `not_found`.

**Comment by melbahja** [comment]
Maybe fiber needs `NotFoundHandler`?

**Comment by kiyonlin** [comment]
> Maybe fiber needs `NotFoundHandler`?

Maybe you should make a feature issue.

**Comment by codemicro** [comment]
> I was gonna pass the tests, but you closed the PR quickly.

The problem with this is that if you need to change the test cases, you're introducing changes that will also break any apps using Fiber when they're upgraded to a new minor or patch version of the framework. This is the sort of change that would go in the v3 release of Fiber, which isn't planned for some time yet.

@melbahja

**Comment by Fenny** [comment]
> Maybe fiber needs `NotFoundHandler`?

<https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses>

**Pull request closed without merging**
