### PR TITLE
♻️ logger/middleware colorize logger error message #2593

### PR DESCRIPTION
**Pull request by ReneWerner87**
## Description

Color for the error tag of the logger and error tag by default in default format

### CODE REVIEW

**Comment by ReneWerner87** [comment]
if you have any ideas to prevent the error from taking up space in the format if there is none, please feel free to add it to the branch

**Comment by sixcolors** [comment]
@ReneWerner87 why not align with [morgan](https://expressjs.com/en/resources/middleware/morgan.html)?

**Review by sixcolors — APPROVED** [review]
LGTM!

**Comment by sixcolors** [comment]
> LGTM!

Although I'm not 💯 on error being in the default log format.

**Comment by gaby** [comment]
I think for v2 its fine, for v3 we can have a discussion with a path forward

**Review by gaby — APPROVED** [review]

**Pull request merged**
