### PR TITLE
docs: update compatibility as per #1994

### PR DESCRIPTION
**Pull request by GalvinGao**
## Description

As per discussed in https://discord.com/channels/704680098577514527/704680099320037448/1011520251336339487

## Type of change

Please delete options that are not relevant.

- [x] This PR itself is a documentation update

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by efectn** [comment]
Can you update other READMEs

**Comment by ReneWerner87** [comment]
> Can you update other READMEs

@GalvinGao

**Comment by GalvinGao** [comment]
> > Can you update other READMEs
> 
> 
> 
> @GalvinGao 

Sure. Will do in a couple of hours.

**Comment by GalvinGao** [comment]
See #2043 instead please :)

**Pull request closed without merging**
