### PR TITLE
Add ${port} logger variable

### LINKED ISSUE #1447: 🚀 Add ${port} variable in middleware/logger
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
I'd like to be able to log remote user's address **with port**, not just ip.

**Additional context**
Sometimes, when notifying and an ISP about an incident, they'll ask for the client's ip **and** port, as a lot of ISP use CGNAT for distributing IP for their users. Also, if one use NAT within a company (e.g. in case of a DMZ behind NAT), they'll need the port to identify local users too.

I came up with the following patch, but as I'm not familiar with the codebase, nor am I a programmer, I didn't create a PR. If you think this might be an acceptable solution, I'll create it.

```diff
diff --git a/ctx.go b/ctx.go
index fbbed651..9b446a1e 100644
--- a/ctx.go
+++ b/ctx.go
@@ -13,6 +13,7 @@ import (
        "io"
        "mime/multipart"
        "net/http"
+       "net"
        "path/filepath"
        "reflect"
        "strconv"
@@ -540,6 +541,17 @@ func (c *Ctx) Hostname() string {
        return c.app.getString(c.fasthttp.Request.URI().Host())
 }

+// Addr returns the remote address of the request.
+func (c *Ctx) Addr() net.Addr {
+       return c.fasthttp.RemoteAddr()
+}
+
+// Port returns the remote port of the request.
+func (c *Ctx) Port() string {
+       port := c.Addr().(*net.TCPAddr).Port
+       return strconv.Itoa(port)
+}
+
 // IP returns the remote IP address of the request.
 // Please use Config.EnableTrustedProxyCheck to prevent header spoofing, in case when your app is behind the proxy.
 func (c *Ctx) IP() string {
@@ -547,7 +559,7 @@ func (c *Ctx) IP() string {
                return c.Get(c.app.config.ProxyHeader)
        }

-       return c.fasthttp.RemoteIP().String()
+       return c.Addr().(*net.TCPAddr).IP.String()
 }

 // IPs returns an string slice of IP addresses specified in the X-Forwarded-For request header.
diff --git a/middleware/logger/logger.go b/middleware/logger/logger.go
index a3aeed3d..5bae4932 100644
--- a/middleware/logger/logger.go
+++ b/middleware/logger/logger.go
@@ -24,6 +24,7 @@ const (
        TagTime              = "time"
        TagReferer           = "referer"
        TagProtocol          = "protocol"
+       TagPort              = "port"
        TagIP                = "ip"
        TagIPs               = "ips"
        TagHost              = "host"
@@ -209,6 +210,8 @@ func New(config ...Config) fiber.Handler {
                                return buf.WriteString(c.Protocol())
                        case TagPid:
                                return buf.WriteString(pid)
+                       case TagPort:
+                               return buf.WriteString(c.Port())
                        case TagIP:
                                return buf.WriteString(c.IP())
                        case TagIPs:
```

### PR DESCRIPTION
**Pull request by markkrj**
Fix #1447 

* Added function c.Port() which get port from c.fasthttp.RemoteAddr()
* Added `port` variable to middleware/logger

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Could you add a description in the readme and a unittest fpr for this?

**Comment by markkrj** [comment]
@ReneWerner87 can you check if it's ok now?

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
Please check

**Comment by markkrj** [comment]
@ReneWerner87 Simplified the code and ran tests locally with `act`, might be working now

**Comment by ReneWerner87** [comment]
@markkrj can you please update https://github.com/gofiber/docs/blob/master/api/middleware/logger.md with the new variable

**Comment by markkrj** [comment]
@ReneWerner87 I sure can do that, but I think linking that to https://github.com/gofiber/fiber/blob/master/middleware/logger/README.md is a better solution as it is more up to date... There is more changes to logger that are not documented in gofiber/docs. IMHO you should keep docs only in one place to avoid such discrepancy.

**Comment by ReneWerner87** [comment]
just tested it, in the gitbook would then show an external link, so we have to copy it
https://github.com/gofiber/docs/commit/c980089b3966e0a9fb8e475fdb8e3bf4812199b4
https://github.com/gofiber/docs/commit/68a308201a1f1ad1f666596479bbdf93c2d4a1e0

**Pull request merged**
