### PR TITLE
✨ V3 Alpha Trial (95% inspired by Express)

### PR DESCRIPTION
**Pull request by balcieren**
## **Tiny Fiber** 👌

Firstly, I know `v3-beta` branch also I support it. But I want to try close to full `Express.JS` inspired. I have done a lot of things. I will share information about "what I do", "what I will" etc. If you follow [Express Doc](https://expressjs.com/en/5x/api.html) you can give support.

- [x] Replaced v2 with v3
- [x] Moved some internal packages to go.mod
- [x] Upgraded go version to 1.19
- [x] Fixed deprecated ioutil errors
- [X] Removed hooks. 
- [x] Added new mounting app system and fixed bugs from old version
- [ ] Sub in sub mounting
- [x] Added mount tests and benchmarks
- [x] Combined `ListenTLS()` and `ListenMutualTLS()` on `Listen()` function
- [x] Updated new Listen function's tests  
- [x] Added `Host()` Context
- [x] Added `Host()` tests and benchmarks
- [x] Fixed `HostName()` function. It should be return host without port number 
- [X] Updated `HostName()` function's test
- [X] Removed `Group()` and `Route()` functions
- [X] Added new fiber router system **(We need better and cleaner solution for router)**
- [ ] register mounted app's router's stack
- [x] Added app.Router ([express app.router](https://expressjs.com/en/5x/api.html#app.router))
- [x] Fixed not working router config 
- [ ] Improved router nested params performance
- [x] Added router tests and benchmarks
- [ ] Client refactor https://github.com/gofiber/fiber/pull/1986

- [x] Added Express Route ([express route](https://expressjs.com/en/5x/api.html#app.route))
- [x] Added `Route()` tests and benchmarks
- [ ] Added `Render()` function to app ([express render](https://expressjs.com/en/5x/api.html#app.render))
- [ ] Added `Render()` tests and benchmarks
- [x] Added ctx.Render callback function ([express response.render' callback](https://expressjs.com/en/5x/api.html#res.render))
- [x] Added ctx.Render callback test
- [ ] Added `CookieParser()` function to Context
- [ ] Added `Param()` function to App and Router ([express param](https://expressjs.com/en/5x/api.html#app.param))
- [x] Added back redirect feature to `Redirect()` [express redirect](https://expressjs.com/en/5x/api.html#res.redirect)
- [x] Fixed Context `Render()` bug
- [x] New static system 
- [x] We can do like this [express app engine](https://expressjs.com/en/5x/api.html#app.engine) for template engine
- [x] ErrorHandler was moved to Use() function
```go
func main() {
	app := New()

	app.Use(func(c *Ctx, err error) error {
		return c.Status(200).SendString("hi, i'm an custom error")
	})	
}
```
- [x] Added router error handler
 ```go
func main() {
	app := New()
	router := NewRouter()

	app.Use("/router", router)

	router.Use(func(c *fiber.Ctx, err error) error {
		return c.Status(500).SendString("I'm router error handler")
	})
}
```
- [x] Multi prefix for mounting, router and paths
```go
func main() {
	app := fiber.New()
	router := fiber.NewRouter()

	app.Use([]string{"/fiber", "/amazing"}, router)
	router.Get("/", func(c *fiber.Ctx) error {
		return c.JSON("fiber is amazing👌")
	})
}
```
- [x] Nested params for router
```go
func main() {
	app := fiber.New()
	router := fiber.NewRouter(fiber.RouterConfig{
		MergeParams: true,
	})

	app.Use("/router/:id", router)
	router.Get("/:name", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{
			"id":   c.Params("id"),
			"name": c.Params("name"),
		})
	})
}
```
- [ ] Error Handlers according to paths
 ```go
func main() {
	app := New()

       // This error handler is gonna work for `/fiber` path 
	app.Use("/fiber", func(c *Ctx, err error) error {
		return c.Status(500).SendString("I'm error handler for `/fiber` path")
	})

	app.Get("/fiber", func(c *fiber.Ctx) error {
               return fiber.NewError(500, "")
        })
}
```
- [x] Event Emitter System instead of Hooks (inspired by express)
```go
func main() {
	app := fiber.New()

	app.On("greet", func(data byte) {
		///...
	})

	app.Get("/", func(c *fiber.Ctx) error {

		c.Emit("greet", fiber.Map{
			"message": "hi fiber ",
		})
		return c.JSON("👋")
	})

	app.Listen(":3000")
}
```

### CODE REVIEW

**Comment by Trim21** [comment]
maybe we should create a v2 branch before merge v3 into master…

**Comment by balcieren** [comment]
@Trim21 Firstly we should fix known problems for v2. We should catch stable v2 before v3 ...

**Comment by ReneWerner87** [comment]
> maybe we should create a v2 branch before merging v3 into master…

i agree
we will not transfer at this time the code to the master

first version 3 must be ready

**Comment by wangjq4214** [comment]
Do we need to add some issues to track these tasks? It seems that the above features are not fully covered in the current issue.

**Comment by efectn** [comment]
I think this PR should have splitted into the PRs and issues that targets v3-beta

**Comment by ReneWerner87** [comment]
@balcieren can you create a pull request with the v3-beta target

**Comment by balcieren** [comment]
> can you create a pull request with the v3-beta target

v3-beta started to go away from inspired express. I think when express.js user came to fiber, will meet different things. A lot of different features are not meaning users will use them. When I was using express.js, everything was enough. I think fiber also should be like that. I think when we go away from express doc, we can lost a lot of users. We should decide to choose true way.

**Comment by balcieren** [comment]
I am closing this pr, some features can add to version 3 inspiring by this pr

**Pull request closed without merging**
