### PR TITLE
Improve json

### PR DESCRIPTION
**Pull request by kiyonlin**
I made adjustments to `ctx.JSON`, which can improve performance by about ~~30%~~ 20%. 

And the impacts are:
- Regardless of whether json serialization is successful or not, `response body` will be reset
- ~~The json serialization result will append an extra `\n`(see [reason in stdlib](https://github.com/golang/go/blob/release-branch.go1.14/src/encoding/json/stream.go#L211-L217)) , which I personally think will not have a destructive effect~~

This PR retains the old `ctx.JSONOld` for benchmark comparison. You can execute `go test -v -run=^$ -bench="Benchmark_Ctx_JSON(O|$)" -benchmem -count=4
`View results:
```bash
# on my machine
go test -v -run=^$ -bench="Benchmark_Ctx_JSON(O|$)" -benchmem -count=4
goos: darwin
goarch: amd64
pkg: github.com/gofiber/fiber
Benchmark_Ctx_JSON
Benchmark_Ctx_JSON-8 2703946 442 ns/op 32 B/op 1 allocs/op
Benchmark_Ctx_JSON-8 2773329 434 ns/op 32 B/op 1 allocs/op
Benchmark_Ctx_JSON-8 2753611 436 ns/op 32 B/op 1 allocs/op
Benchmark_Ctx_JSON-8 2756508 434 ns/op 32 B/op 1 allocs/op
Benchmark_Ctx_JSONOld
Benchmark_Ctx_JSONOld-8 2088817 570 ns/op 80 B/op 3 allocs/op
Benchmark_Ctx_JSONOld-8 2095932 570 ns/op 80 B/op 3 allocs/op
Benchmark_Ctx_JSONOld-8 2111797 577 ns/op 80 B/op 3 allocs/op
Benchmark_Ctx_JSONOld-8 2090282 563 ns/op 80 B/op 3 allocs/op
PASS
ok github.com/gofiber/fiber 14.568s
```

remove extra '\n' part is co-authored with @ReneWerner87 
```go
	b := ctx.Fasthttp.Response.Body()
	if end := len(b) - 1; end >= 0 && b[end] == '\n' {
		// remove extra '\n' added by encoder.Encode
		ctx.Fasthttp.Response.SetBodyRaw(b[:end])
	}
```

**If this RP is ~~approved~~ ready to be merged, I will delete the comparison code.** @Fenny

### CODE REVIEW

**Comment by kiyonlin** [comment]
All things above is **bullshit** :sob:

`json.Marshal(data)` and `c.JSON(&data)` are the best!

```bash
goos: darwin
goarch: amd64
pkg: github.com/gofiber/fiber
Benchmark_Ctx_JSON
Benchmark_Ctx_JSON-8             3430592               349 ns/op              32 B/op          1 allocs/op
Benchmark_Ctx_JSON-8             3339294               354 ns/op              32 B/op          1 allocs/op
Benchmark_Ctx_JSON-8             3482070               356 ns/op              32 B/op          1 allocs/op
Benchmark_Ctx_JSON-8             3441146               348 ns/op              32 B/op          1 allocs/op
```

**Comment by ReneWerner87** [comment]
Are you sure? I think maybe the bench is now wrong, because the data is still adjusted in the second iteration

**Comment by kiyonlin** [comment]
> Are you sure? I think maybe the bench is now wrong, because the data is still adjusted in the second iteration


I’m not sure if something went wrong with the benchmark.  Maybe this was an accident.

**Comment by ReneWerner87** [comment]
JSON - OLD:
```go
Benchmark_Ctx_JSON-12        3559738         329 ns/op        80 B/op         3 allocs/op
Benchmark_Ctx_JSON-12        3472398         331 ns/op        80 B/op         3 allocs/op
Benchmark_Ctx_JSON-12        3565225         383 ns/op        80 B/op         3 allocs/op
```
JSON - NEW:
```go
Benchmark_Ctx_JSON-12        4729792         242 ns/op        64 B/op         2 allocs/op
Benchmark_Ctx_JSON-12        4955448         244 ns/op        64 B/op         2 allocs/op
Benchmark_Ctx_JSON-12        4777286         242 ns/op        64 B/op         2 allocs/op
```
JSONP - OLD:
```go
Benchmark_Ctx_JSONP-12       2650819         447 ns/op        80 B/op         3 allocs/op
Benchmark_Ctx_JSONP-12       2660439         450 ns/op        80 B/op         3 allocs/op
Benchmark_Ctx_JSONP-12       2624751         460 ns/op        80 B/op         3 allocs/op
```
JSONP - NEW:
```go
Benchmark_Ctx_JSONP-12       3388604         354 ns/op        64 B/op         2 allocs/op
Benchmark_Ctx_JSONP-12       3385488         356 ns/op        64 B/op         2 allocs/op
Benchmark_Ctx_JSONP-12       3380559         353 ns/op        64 B/op         2 allocs/op
```

**Comment by ReneWerner87** [comment]
Format with JSON - OLD:
```go
Benchmark_Ctx_Format_JSON-12       3559171         333 ns/op        32 B/op         2 allocs/op
Benchmark_Ctx_Format_JSON-12       3441303         335 ns/op        32 B/op         2 allocs/op
Benchmark_Ctx_Format_JSON-12       3597136         337 ns/op        32 B/op         2 allocs/op
```
Format with JSON - NEW:
```go
Benchmark_Ctx_Format_JSON-12       4790078         248 ns/op        16 B/op         1 allocs/op
Benchmark_Ctx_Format_JSON-12       4799577         249 ns/op        16 B/op         1 allocs/op
Benchmark_Ctx_Format_JSON-12       4509889         250 ns/op        16 B/op         1 allocs/op
```

**Pull request merged**
