### PR TITLE
🩹 Fix: improper query/body parsing with embedded structs

### PR DESCRIPTION
**Pull request by devhsoj**
## Description

This PR fixes improper bodyparser/query parsing when using embedded structs within a schema.

Related to #2859 

## Type of change

- [x] Enhancement (improvement to existing features and functionality)
- [ ] Documentation update (changes to documentation)
- [ ] Performance improvement (non-breaking change which improves efficiency)
- [ ] Code consistency (non-breaking change which improves code reliability and robustness)

## Summary by CodeRabbit

- **Refactor**
	- Enhanced comparison logic in `equalFieldType` to better handle embedded struct fields.
- **New Features**
	- Improved parsing logic for various data formats by including the `Names` field in the process.

### CODE REVIEW

**Comment by gaby** [comment]
@devhsoj This needs a unit-test using the example provided in #2859 That way we can verify it fixes the issue

**Comment by devhsoj** [comment]
@gaby 

Thanks for the feedback, I just pushed updates to the `Test_Ctx_Parsers` unit tests that adds an embedded struct `TestEmbeddedStruct` to the `TestStruct` struct used for parsing that verifies that my changes work against an identical example to #2859.

**Review by ReneWerner87 — APPROVED** [review]

**Comment by gaby** [comment]
@ReneWerner87 My only concern is codecov shows that those new lines are not covered by the updated tests.

**Comment by ReneWerner87** [comment]
since we will be refactoring later anyway, it's not a big deal, otherwise we will increase the coverage even later

**Pull request merged**
