### PR TITLE
optimize: latency use lowest time unit in logger middleware

### PR DESCRIPTION
**Pull request by li-jin-gou**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
Explain the *details* for making this change. What existing problem does the pull request solve?

Fixes https://github.com/gofiber/fiber/issues/2258

## Type of change

Please delete options that are not relevant.

- [x] New optimize(non-breaking change which adds functionality)

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by li-jin-gou** [comment]
There is a datarace here and I will try to fix it. https://github.com/gofiber/fiber/actions/runs/3617013466/jobs/6095488826

**Comment by ReneWerner87** [comment]
let me know when the pull request is mergable and you have found or fixed the datarace problem

**Comment by li-jin-gou** [comment]
> let me know when the pull request is mergable and you have found or fixed the datarace problem

I haven't found the cause of this datarace yet, so I'll mention a separate PR fix😶

**Review by ReneWerner87 — APPROVED** [review]

**Comment by MartinHotmann** [comment]
Thanks mate :)

**Pull request merged**
