### PR TITLE
fix(middleware/session): mutex for thread safety

### PR DESCRIPTION
**Pull request by sixcolors**
This pull request adds a mutex to the session middleware to ensure thread safety when accessing session data. The mutex is used to protect non-data fields and prevent race conditions. This improves the reliability and stability of the session middleware.

### CODE REVIEW

**Comment by gaby** [comment]
@sixcolors Did you try running it with `make longtest` ?

**Comment by sixcolors** [comment]
> @sixcolors Did you try running it with `make longtest` ?

yes

**Comment by sixcolors** [comment]
@coderabbitai full review

**Review by ReneWerner87 — APPROVED** [review]

**Comment by efectn** [comment]
I still see some data-races. Maybe it's caused because we acquired a session and not released somewhere?

```sh
╰─$ go test . -race -count=20                                                                                                                                          1 ↵
==================
WARNING: DATA RACE
Write at 0x00c000688318 by goroutine 167:
  github.com/gofiber/fiber/v3/middleware/session.(*Store).Get()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/store.go:82 +0x384
  github.com/gofiber/fiber/v3/middleware/session.Test_Session_Concurrency.func1()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session_test.go:880 +0x14d

Previous read at 0x00c000688318 by goroutine 147:
  github.com/gofiber/fiber/v3/middleware/session.(*Session).ID()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session.go:69 +0x8f
  github.com/gofiber/fiber/v3/middleware/session.Test_Session_Store_Reset()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session_test.go:305 +0x2d1
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /usr/lib/go/src/testing/testing.go:1742 +0x44

Goroutine 167 (running) created at:
  github.com/gofiber/fiber/v3/middleware/session.Test_Session_Concurrency()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session_test.go:875 +0xab
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /usr/lib/go/src/testing/testing.go:1742 +0x44

Goroutine 147 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:1742 +0x825
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:2161 +0x85
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:2159 +0x8be
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:2027 +0xf17
  main.main()
      _testmain.go:85 +0x2bd
==================
--- FAIL: Test_Session_Cookie_In_Middleware_Chain (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Custom_Config (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Cookie (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Store_Reset (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Regenerate (0.00s)
    --- FAIL: Test_Session_Regenerate/set_fresh_to_be_true_when_regenerating_a_session (0.00s)
        testing.go:1398: race detected during execution of test
--- FAIL: Test_Store_Get (0.00s)
    --- FAIL: Test_Store_Get/session_should_be_re-generated_if_it_is_invalid (0.00s)
        testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Concurrency (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Save (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Store_getSessionID (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Deletes_Single_Key (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Destroy (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Types (0.01s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Reset (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Save_Expiration (0.00s)
    --- FAIL: Test_Session_Save_Expiration/save_to_cookie (5.02s)
        testing.go:1398: race detected during execution of test
==================
WARNING: DATA RACE
Write at 0x00c00041b578 by goroutine 766:
  github.com/gofiber/fiber/v3/middleware/session.(*Store).Get()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/store.go:82 +0x384
  github.com/gofiber/fiber/v3/middleware/session.Test_Session_Concurrency.func1()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session_test.go:915 +0x3db

Previous read at 0x00c00041b578 by goroutine 733:
  github.com/gofiber/fiber/v3/middleware/session.(*Session).ID()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session.go:69 +0x8f
  github.com/gofiber/fiber/v3/middleware/session.Test_Session_Store_Reset()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session_test.go:305 +0x2d1
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /usr/lib/go/src/testing/testing.go:1742 +0x44

Goroutine 766 (running) created at:
  github.com/gofiber/fiber/v3/middleware/session.Test_Session_Concurrency()
      /home/efectn/Devel/fiber-v3-constraint/middleware/session/session_test.go:875 +0xab
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /usr/lib/go/src/testing/testing.go:1742 +0x44

Goroutine 733 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:1742 +0x825
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:2161 +0x85
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1689 +0x21e
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:2159 +0x8be
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:2027 +0xf17
  main.main()
      _testmain.go:85 +0x2bd
==================
--- FAIL: Test_Store_Get (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Store_Reset (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Save (0.00s)
    --- FAIL: Test_Session_Save/save_to_header (0.00s)
        testing.go:1398: race detected during execution of test
    --- FAIL: Test_Session_Save/save_to_cookie (0.00s)
        testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Regenerate (0.00s)
    --- FAIL: Test_Session_Regenerate/set_fresh_to_be_true_when_regenerating_a_session (0.00s)
        testing.go:1398: race detected during execution of test
--- FAIL: Test_Store_getSessionID (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Deletes_Single_Key (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Concurrency (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Cookie_In_Middleware_Chain (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Destroy (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Reset (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Types (0.00s)
    testing.go:1398: race detected during execution of test
--- FAIL: Test_Session_Save_Expiration (0.00s)
    --- FAIL: Test_Session_Save_Expiration/save_to_cookie (5.01s)
        testing.go:1398: race detected during execution of test
FAIL
FAIL    github.com/gofiber/fiber/v3/middleware/session  100.314s
FAIL
```

**Pull request merged**
