### PR TITLE
🔧 fix(middleware/csrf): unmatched token returns nil error

### LINKED ISSUE #1666: 🐛 bug(middleware/csrf): unmatched token returns nil error
**Fiber version**
v2.23.0
**Issue description**
middleware/csrf: unmatched token returns nil error

### PR DESCRIPTION
**Pull request by sixcolors**
This PR closes #1666 

when the following is true

``if manager.getRaw(token) == nil ``

err will be nil otherwise it would have returned on line 40.

So we must set the error before calling `cfg.ErrorHandler(c, err)`

### CODE REVIEW

**Comment by ReneWerner87** [comment]
thx, could you please. provide a unittest for this

**Comment by sixcolors** [comment]
The current unit tests work unchanged as the error handler was still called, but just had a nil err value. The default err handler still returned 403 as it did not check the err value. 

Do you have a suggestion of what unit test change you’d like for retiring a non nil error?

**Comment by ReneWerner87** [comment]
since you have made an adjustment, the expectation should also change, otherwise the unittests that passed before are incomplete, if despite the change the external parameters do not change

i'm for extending the test to check the error text, because that's what you expect, if the token doesn't match, you want to be informed about that too

**Comment by liaohongxing** [comment]
I hope to change Render(io.Writer, string, interface(), ...string) error to Render(*Ctx, io.Writer, string, interface(), ...string) error in the next major version

Add a Ctx parameter, interface() can be changed to Map, it doesn’t matter

@ReneWerner87

**Comment by sixcolors** [comment]
> since you have made an adjustment, the expectation should also change, otherwise the unittests that passed before are incomplete, if despite the change the external parameters do not change
> 
> i'm for extending the test to check the error text, because that's what you expect, if the token doesn't match, you want to be informed about that too

ack

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
