### PR TITLE
:bug: fix: treat case for possible timer memory leak

### LINKED ISSUE #2482: 🐛 [Bug]: Potential leak in sleep.go
### Bug Description

I notice the ctx.Done() needs a cancel function to unblock the statement of ctx.Done in https://github.com/gofiber/fiber/blob/master/internal/gopsutil/common/sleep.go#L13, since the case may block forever if the case not met.
  I was wondering if this may leak the goroutine where the ctx.Done() locates?

Maybe what I said is not right, thank you for taking a look.

### How to Reproduce

.

### Expected Behavior

.

### Fiber Version

v2.40.1

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by luk3skyw4lker**
## Description

It was reported in the gopsutil a possible memory leak for the Sleep function, the fix is to in case of the timer being cancelled by the context, checking if the timer isn't stopped and stoping it.

Fixes #2482 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by gaby** [comment]
This is an upstream fix from here: shirou/gopsutil#1475

**Review by gaby — APPROVED** [review]
LGTM

**Comment by gaby** [comment]
Thanks! @luk3skyw4lker

**Review by sixcolors — APPROVED** [review]
LGTM!

see: https://github.com/shirou/gopsutil/pull/1475

**Review by efectn — APPROVED** [review]

**Pull request merged**
