### PR TITLE
add session interface

### PR DESCRIPTION
**Pull request by hendratommy**
PR for #479 if it's approved

### CODE REVIEW

**Comment by ReneWerner87** [comment]
shouldn't the session instance stay the same when setting ?(@hendratommy ) think using a reference would be good

**Comment by hendratommy** [comment]
@ReneWerner87 
the user session lifetime is only per request, and we will to clear it upon releasing the `ctx` since the `ctx` might be reused by different user.
we only provide the session interface not the concrete session store (or the factory) itself, and we might not want to depend on `fiber/session` directly.
the reference to the store should be managed by the middleware or user land code, for example:
```go
sessions := session.New()
// below handler might be provided by the middleware
app.Use("/web", func(c *fiber.Ctx) {
    store := sessions.Get(c)
    defer store.Save()
    c.SetSession(store)
    c.Next()
})
```
different session factory, might have have their own mechanism about how to get the user's session and how to save them.
how about it?

**Comment by ReneWerner87** [comment]
i mean actually only that a copy of the instance is made if it is set with the setter without reference.

with reference its the same instance
```go
type TestStr struct {
	testValue int
}
a := TestStr{};
a.testValue = 3;
fmt.Println(a.testValue);
func(b *TestStr) {
	b.testValue = 6
	fmt.Println(b.testValue);
	return
}(&a)
fmt.Println(a.testValue);
// output:
// 3
// 6
// 6 <-
```

without reference its a different instance
```go
type TestStr struct {
	testValue int
}
a := TestStr{};
a.testValue = 3;
fmt.Println(a.testValue);
func(b TestStr) {
	b.testValue = 6
	fmt.Println(b.testValue);
	return
}(a)
fmt.Println(a.testValue);
// output:
// 3
// 6
// 3 <-
```

would be cool when you change it to 
```go
func (ctx *Ctx) SetSession(session *Session) {
// code
}

func (ctx *Ctx) Session() *Session {
// code
}
```

**Comment by ReneWerner87** [comment]
image
there can already be different instances between the requests, but you should not make a copy of them when you set it in the ctx

as you can see in the image, in all properties the object instances contain is a reference to it

for the fasthttp requestctx it is always different, but it is referenced so that it is the same as the one used in the fasthttp process and our process

**Comment by thomasvvugt** [comment]
I've looked into this issue and proposal as well, but it seems to me this is a bit of over-engineering.
We specifically developed a middleware (library) for sessions since not every application built with Fiber would be using this feature.
Eventhough I like the idea of wrapping the Fiber application along with the session middleware in a struct with setters and getters, I don't think this should be a feature which should be implementer in Fiber itself but rather should be handler by a developer using Fiber as a framework to build their application on.

Let me explain further using a code example:
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/session"
)

type App struct {
	Fiber *fiber.App
	Sessions *session.Session
	Store *session.Store
}

func main() {
	app := App{
		Fiber: fiber.New(),
		Sessions: session.New(),
	}

	app.Fiber.Use(func(c *fiber.Ctx) {
		app.Store = app.Sessions.Get(c)
		defer app.Store.Save()
		c.Next()
	})

	app.Fiber.Get("/", func(c *fiber.Ctx) {
		app.Store.ID()                   // returns session id
		app.Store.Destroy()              // delete storage + cookie
		app.Store.Get("john")            // get from storage
		app.Store.Regenerate()           // generate new session id
		app.Store.Delete("john")         // delete from storage
		app.Store.Set("john", "doe")     // save to storage
	})
}
```

**Comment by hendratommy** [comment]
@thomasvvugt 
agree, i like to see it as placeholder, we have the way but not the implementor. it's more or less the same with render, we provide the render function but the template itself is not implemented in the main package.

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/issues/479#issuecomment-652799369

**Pull request closed without merging**
