### PR TITLE
Update fasthttp version to resolve brotli warnings

### PR DESCRIPTION
**Pull request by milosgajdos**
**Please provide enough information so that others can review your pull request:**

[github.com/andybalholm/brotli retracted v1.0.1 release](https://github.com/andybalholm/brotli/commit/5376c15dde3fd4247febd5a3b4ac9708d2d6faff) due to discovering Go panics. Unfortunately, the version of [fasthttp](https://github.com/valyala/fasthttp) that is a direct dependency of fiber [used v1.0.1 as a direct dependency](https://github.com/valyala/fasthttp/blob/v1.23.0/go.mod#L6) which in turn causes legitimate warnings when getting the fiber Go module:

```
$ go get github.com/gofiber/fiber/v2
go: downloading github.com/gofiber/fiber/v2 v2.10.0
go: downloading golang.org/x/sys v0.0.0-20210225134936-a50acf3fe073
go: warning: github.com/andybalholm/brotli@v1.0.1: retracted by module author: occasional panics and data corruption
go: to switch to the latest unretracted version, run:
	go get github.com/andybalholm/brotli@latest
go get: added github.com/gofiber/fiber/v2 v2.10.0
```

**Explain the *details* for making this change. What existing problem does the pull request solve?**

This PR updates `fasthttp` to `v1.25.0` that [ships with updated brotli version](https://github.com/valyala/fasthttp/blob/v1.25.0/go.mod#L6).

**NOTE:** `v1.24.0` of `fasthttp` still depends on the broken `brotli` module, hence this PR updates `fasthttp` to `v1.25.0`

### CODE REVIEW

**Comment by hi019** [comment]
Thanks for the PR! Running tests now...

**Comment by ReneWerner87** [comment]
Issues with the pprof content type

**Comment by ReneWerner87** [comment]
hmm, it should be 
"text/html; charset=utf-8"
https://golang.org/src/net/http/pprof/pprof.go?s=11637:11687#L377

and fasthttp part looks also good
https://github.com/valyala/fasthttp/blob/master/fasthttpadaptor/adaptor.go#L62-L64

**Comment by ReneWerner87** [comment]
found the problem:

image
there are 2 headers for contentType

**Comment by ReneWerner87** [comment]
image

**Comment by milosgajdos** [comment]
Hmm, this is a bit strange. I get no errors on the go version I mentioned in the PR description:

```
$ go test
PASS
ok  	github.com/gofiber/fiber/v2/middleware/pprof	2.193s
$ go test -v
=== RUN   Test_Non_Pprof_Path
--- PASS: Test_Non_Pprof_Path (0.00s)
=== RUN   Test_Pprof_Index
--- PASS: Test_Pprof_Index (0.00s)
=== RUN   Test_Pprof_Subs
=== RUN   Test_Pprof_Subs/cmdline
=== RUN   Test_Pprof_Subs/profile
=== RUN   Test_Pprof_Subs/symbol
=== RUN   Test_Pprof_Subs/trace
=== RUN   Test_Pprof_Subs/allocs
=== RUN   Test_Pprof_Subs/block
=== RUN   Test_Pprof_Subs/goroutine
=== RUN   Test_Pprof_Subs/heap
=== RUN   Test_Pprof_Subs/mutex
=== RUN   Test_Pprof_Subs/threadcreate
--- PASS: Test_Pprof_Subs (2.03s)
    --- PASS: Test_Pprof_Subs/cmdline (0.00s)
    --- PASS: Test_Pprof_Subs/profile (1.00s)
    --- PASS: Test_Pprof_Subs/symbol (0.00s)
    --- PASS: Test_Pprof_Subs/trace (1.00s)
    --- PASS: Test_Pprof_Subs/allocs (0.00s)
    --- PASS: Test_Pprof_Subs/block (0.02s)
    --- PASS: Test_Pprof_Subs/goroutine (0.00s)
    --- PASS: Test_Pprof_Subs/heap (0.00s)
    --- PASS: Test_Pprof_Subs/mutex (0.00s)
    --- PASS: Test_Pprof_Subs/threadcreate (0.00s)
=== RUN   Test_Pprof_Other
--- PASS: Test_Pprof_Other (0.00s)
PASS
ok  	github.com/gofiber/fiber/v2/middleware/pprof	2.191s
```

When I change the content type back to `text/html` I get this error:

```
$ go test -v
=== RUN   Test_Non_Pprof_Path
--- PASS: Test_Non_Pprof_Path (0.00s)
=== RUN   Test_Pprof_Index
    assertions.go:59:
        Test:       Test_Pprof_Index
        Trace:      pprof_test.go:44
        Expect:     text/html                     (string)
        Result:     text/plain; charset=utf-8     (string)
...
...
```

**Comment by ReneWerner87** [comment]
https://github.com/valyala/fasthttp/pull/1021

this change leads to the duplicate headers, because in the adapter the Header.Set is not used anymore, the header is not set with SetCanonical and therefore SetContentTypeBytes and so ContentType is empty and will be written at the end when writing the header with the default header

i will open a bug report at fasthttp

**Comment by ReneWerner87** [comment]
> Blowing test cache doesn't chang this
yeah, because its a real fasthttp bug^^

**Comment by milosgajdos** [comment]
Ah, got it.

**Comment by ReneWerner87** [comment]
https://github.com/valyala/fasthttp/pull/1021#issuecomment-851020279

**Comment by milosgajdos** [comment]
Perfect! Thanks for looking into this. I'm happy to take that change out of the PR.

**Comment by ReneWerner87** [comment]
lets wait for 
https://github.com/valyala/fasthttp/pull/1036

**Comment by ReneWerner87** [comment]
@milosgajdos could you update with 1.26
https://github.com/valyala/fasthttp/releases/tag/v1.26.0

**Comment by milosgajdos** [comment]
I've rebased to clean up the git history a bit.

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
