### PR TITLE
add ulid routing Constraint

### PR DESCRIPTION
**Pull request by alfadhela**
## Description

Add new constraint for `ulid` using `github.com/oklog/ulid/v2` pkg.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.md#pull-requests-or-commits)

### CODE REVIEW

**Comment by ReneWerner87** [comment]
image
hi, as already mentioned here, we want to include as few dependencies as possible in the core

thanks for the effort, but another solution to minimize this external dependency for everyone would be better for the core
e.g. about the possibility to add other contrains from outside

**Comment by ReneWerner87** [comment]
you are welcome to work on it in the beta branch for version 3

we don't want new feature requests for v2 at the moment, because we want to stop the development there for now

**Comment by alfadhela** [comment]
No problem but is it acceptable if write regexp for ulid instead of using `oklog/ulid`pkg.

**Comment by ReneWerner87** [comment]
well, then the exam would only be half right
since there are many possibilities for contrains, but we shouldn't cover them all within the core, i think you should make them expandable

we can't possibly include all patterns, such as uuidv3, uuidv4, ulid etc.

to solve the problem on your side/project, however, you could use a regex contrain in your route

**Comment by alfadhela** [comment]
It's a solution.
If I can suggest to make route constraint plugable similar to `go-playground/validator`. 
I'll try to create a PR if it's acceptable.

**Comment by alfadhela** [comment]
Hi @ReneWerner87,
After trying to add `regex(expression)` I faced a new issue, in path all constraints will be lower-case. the solution is to add `config.CaseSensitive = true` to `fiber.App()` which is not ideal.

**Pull request closed without merging**
