### PR TITLE
🚀 HTTP/2 Feature

### PR DESCRIPTION
**Pull request by balcieren**
Usage :
```go
	app := fiber.New(fiber.Config{
		EnableHTTP2: true, // Default: false
	})

	app.Get("/http11", func(c *fiber.Ctx) error {
		return c.JSON(c.IsHTTP11()) //return true without http2 client support
	})

	app.Get("/http2", func(c *fiber.Ctx) error {
		return c.JSON(c.IsHTTP2()) //return true via http2 client support
	})

	app.ListenTLS(":8080", ".github/testdata/public.crt", ".github/testdata/private.key")
```

Issue #1683

### To Do List

- [x] Add property to app's config.
- [x] Compatible with prefork.
- [x] ListenTLS with HTTP/2.
- [x] ListenMutualTLS with HTTP/2.
- [x] Add IsHTTP2 and IsHTTP11 functions to context.
- [x] HTTP2 client support.
- [x] Add tests.

ZAAAA

### CODE REVIEW

**Comment by gaby** [comment]
@balcieren @efectn Any updates on this?

**Comment by efectn** [comment]
> @balcieren @efectn Any updates on this?

Waiting for:
- https://github.com/dgrr/http2/issues/59
- https://github.com/dgrr/http2/issues/58

**Comment by balcieren** [comment]
> @balcieren @efectn Any updates on this? 

We are waiting to stable version.

**Comment by HiperMaximus** [comment]
Bump

**Comment by mikestopcontinues** [comment]
Bump

**Comment by gaby** [comment]
@mikestopcontinues Sadly, this is blocked by the 2 open PR's mentioned before.

**Comment by MohammadArik** [comment]
> @mikestopcontinues Sadly, this is blocked by the 2 open PR's mentioned before.

do you mean those issues right?

**Comment by efectn** [comment]
Closed the PR due to inactivity of dgrr/http2

**Comment by mikestopcontinues** [comment]
@efectn Is there a plan for what to do instead?

**Comment by efectn** [comment]
> @efectn Is there a plan for what to do instead?

No, we don't have any plan at the moment

**Comment by MindMayhem** [comment]
> > @balcieren @efectn Any updates on this?
> 
> Waiting for:
> 
> * [DATA RACE dgrr/http2#59](https://github.com/dgrr/http2/issues/59)
> * [OMG! it's panic dgrr/http2#58](https://github.com/dgrr/http2/issues/58)

Seems like they are forked http2 and fixed those issues

https://github.com/diamondcdn/fasthttp-http2

**Comment by gaby** [comment]
@efectn Maybe this can be re-evaluated with the fork?

**Comment by efectn** [comment]
> 

Sure

**Pull request closed without merging**
