### PR TITLE
add: params parse

### PR DESCRIPTION
**Pull request by olongfen**
**Hello, This PR is binds the param string to a struct**

**Parse path parameters and body parameters using a struct**
```go 
	app.Put("/user/:id", func(ctx *Ctx) error {
		type User struct {
			// uri
			ID uint `uri:"id" validate:"required"`
			// body
			Username string `json:"username" validate:"required"`
			Age      int    `json:"age"`
		}
		var (
			d = new(User)
		)
		// params parser
		_ = ctx.ParamsParser(d)
		// body parser
		_ = ctx.BodyParser(d)
		// then validate
		validate.Struct(d)
		return nil
	})
```

### CODE REVIEW

**Comment by ReneWerner87** [comment]
- [ ] please add a part in the documentation repository

**Comment by liaohongxing** [comment]
uri tag should be renamed param, similar to Echo Gin in the go ecosystem

considering the existing params(), paramsint(), is it param or params that needs to be discussed

**Comment by olongfen** [comment]
> uri tag should be renamed params , similar to Echo Gin in the go ecosystem
> 
> considering the existing params(), paramsint(), is it param or params that needs to be discussed

> gin  use struct tag   is uri tag ,  path param include many value,so  i think use paramsParser is better
> 
image

**Comment by liaohongxing** [comment]
it is recommended to change to params, consistent with the existing API

```
func (c *Ctx) Params(key string, defaultValue ... string) string
func (c *Ctx) ParamsInt(key string) (int, error)
func (c *Ctx) ParamsParser(out interface{}) error // Tag is params

func (c *Ctx) Query(key string, defaultValue ... string) string
func (c *Ctx) QueryParser(out interface{}) error // Tag is query
```

**Comment by liaohongxing** [comment]
@efectn  what do you think

**Comment by ReneWerner87** [comment]
@olongfen what do you think ? its a valid point

**Comment by olongfen** [comment]
ok

**Pull request merged**
