### PR TITLE
v3: Fix issue with default logger when creating RequestCtx

### LINKED ISSUE #3130: 🐛 [Bug]: FiberApp adaptor initializes fasthttp.RequestCtx with nil logger
### Bug Description

Using Fiber v3.0.0-beta.3, I found that my application was logging errors when serving static content where the file didn't exist when using the FiberApp adaptor middleware to convert the app to a `http.HandlerFunc` interface.

Not a huge issue, but rather a small annoyance.

Example:
2024/09/12 17:19:23 0.001 #0000000100000000 - 0.0.0.0:0<->127.0.0.1:53221 - GET http://localhost:8080/notfound - cannot open file "C:\\path\\to\\file\\does\\not\\exist\\notfound": open C:\\path\\to\\file\\does\\not\\exist\\notfound: The system cannot find the file specified.

It looks like the `fasthttp.RequestCtx` is being initialized with a nil logger in `adaptor.handlerFunc()` causing fasthttp to use the default logger when `fasthttp.RequestCtx.Init()` is invoked

```go
// New fasthttp Ctx
var fctx fasthttp.RequestCtx
fctx.Init(req, remoteAddr, nil) // <-- Nil logger being provided
if len(h) > 0 {
	// New fiber Ctx
	ctx := app.AcquireCtx(&fctx)
	// Execute fiber Ctx
	err := h[0](ctx)
	if err != nil {
		_ = app.Config().ErrorHandler(ctx, err) //nolint:errcheck // not needed
	}
} else {
	// Execute fasthttp Ctx though app.Handler
	app.Handler()(&fctx)
}
```

### How to Reproduce

1. Create a new Fiber App
```go
app := fiber.New()
```
2. Serve static files
```go
app.Get("/*", static.New("/path/to/static/files")
```
3. Convert app to http.HandlerFunc
```go
var h http.Handler = adaptor.FiberApp(app)
```
4. ListenAndServe
```go
server := &http.Server{
    Handler: h,
    Addr: ":8080"
}

panic(server.ListenAndServe())
```
5. Navigate to something in browser that doesn't exist and view logs i.e. localhost:8080/notexists

### Expected Behavior

Expecting the Noop logger to be invoked, leading to no logs being written.

### Fiber Version

v3.0.0-beta.3

### Code Snippet (optional)

```go
package main

import (
	"log"
	"net/http"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/adaptor"
	"github.com/gofiber/fiber/v3/middleware/static"
)

func main() {
	app := fiber.New()

	// Contains an index.html only
	app.Get("/*", static.New("./templates"))

	var h http.Handler = adaptor.FiberApp(app)

	server := &http.Server{
		Handler: h,
		Addr:    ":8080",
	}

	log.Fatal(server.ListenAndServe())
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by gaby**
# Description

- Use `Noop Logger` when creating RequestCtx for Adaptor Middleware.
- Added benchmark for `No Content`.

Fixes #3130 

- [x] Enhancement (improvement to existing features and functionality)

### CODE REVIEW

**Review by ReneWerner87 — APPROVED** [review]
LGTM

**Comment by ReneWerner87** [comment]
> BenchmarkAppendMsgitem

@gaby 
image
there is the problem with the same names in different mw´s
can we rename ?

**Comment by ReneWerner87** [comment]
same for other benches
image

@gaby should we do it in another PR ? then its separated

**Comment by gaby** [comment]
> > BenchmarkAppendMsgitem
> 
> @gaby image there is the problem with the same names in different mw´s can we rename ?

LOL! 😂 Yeah we should rename that, let do a commit here

**Comment by gaby** [comment]
Actually those are auto generated

**Comment by ReneWerner87** [comment]
lets move this discussion to discord

**Pull request merged**
