### PR TITLE
:bug:  fix: multi-byte AppName displays confusion 

### PR DESCRIPTION
**Pull request by li-jin-gou**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
Explain the *details* for making this change. What existing problem does the pull request solve?

Fixes  https://github.com/gofiber/fiber/issues/2147

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have performed a self-review of my own code
- [x]  add all three dependencies to the go mod and remove the copies

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by li-jin-gou** [comment]
Effect1:
image

Effect2:
image

**Comment by ReneWerner87** [comment]
don't know if we should include this in the go.mod

i know fenny does not like dependencies to other packages, so he had made copies

we should treat the 3 packages from mattn the same in any case

so either make copies or put them all as dependencies in the go.mod

@gofiber/maintainers  what do you think?

**Comment by efectn** [comment]
> don't know if we should include this in the go.mod
> 
> i know fenny does not like dependencies to other packages, so he had made copies
> 
> we should treat the 3 packages from mattn the same in any case
> 
> so either make copies or put them all as dependencies in the go.mod
> 
> @gofiber/maintainers what do you think?

I support putting deps into the go.mod but gopsutil is really bloat dependency 🤔

**Comment by ReneWerner87** [comment]
just talking about
https://github.com/mattn/go-colorable
https://github.com/mattn/go-isatty
https://github.com/mattn/go-runewidth

**Comment by efectn** [comment]
> just talking about https://github.com/mattn/go-colorable https://github.com/mattn/go-isatty https://github.com/mattn/go-runewidth

Good idea

**Comment by ReneWerner87** [comment]
@Fenny @hi019 are you okay with this ?

**Comment by ReneWerner87** [comment]
@li-jin-gou can you add all three dependencies to the go mod and remove the copies?

**Review by ReneWerner87 — APPROVED** [review]

**Comment by li-jin-gou** [comment]
> @li-jin-gou can you
> 
> * [ ]  add all three dependencies to the go mod and remove the copies?

Sorry, I just saw it now and I will do so

**Comment by ReneWerner87** [comment]
Thx

**Review by efectn — APPROVED** [review]

**Comment by li-jin-gou** [comment]
I'm going to merge this PR. cc @ReneWerner87 @efectn

**Comment by ReneWerner87** [comment]
> 

give me a few minutes, i will merge it

**Pull request merged**
