### PR TITLE
V3: ctx: make Secure() also report whether a secure connection was established to a trusted proxy

### PR DESCRIPTION
**Pull request by leonklingele**
We had a discussion about this in https://github.com/gofiber/helmet/pull/74.

### CODE REVIEW

**Comment by efectn** [comment]
Don't need this. I'll merge v3 and new helmet changes later

**Comment by leonklingele** [comment]
Why did this get closed? This was in fact a change for v3.

**Comment by efectn** [comment]
> Why did this get closed? This was in fact a change for v3.

This is already exists in master. I regularly merge master into the v3-beta. I'll also merge master and update helmet middleware tomorrow for new changes.

**Comment by leonklingele** [comment]
@efectn is this still on your list?

**Comment by efectn** [comment]
> @efectn is this still on your list?

Yes. I plan to do it tuesday

**Comment by leonklingele** [comment]
Hey @efectn, is this still on your list? 😊

**Comment by efectn** [comment]
> Hey @efectn, is this still on your list? 😊

Yes. Maybe i can merge it weekend or next week.

**Comment by efectn** [comment]
@leonklingele it's done but there are some linting errors. I'll fix them this week

**Pull request closed without merging**
