### PR TITLE
Enable timeout tests

### PR DESCRIPTION
**Pull request by lcd1232**
**Please provide enough information so that others can review your pull request:**

Enable timeout tests.

**Explain the *details* for making this change. What existing problem does the pull request solve?**

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by lcd1232** [comment]
@koddr it looks like Params has data race. Is it ok if I update it by creating copies c.route.Params each call?

**Comment by Fenny** [comment]
The data race seems is caused by the timeout middleware, we use the same logic as fasthttp https://github.com/valyala/fasthttp/blob/master/server.go#L418.
@kiyonlin do you have any idea's left?

**Comment by lcd1232** [comment]
I added time.Sleep for Params test and it has data race too

**Comment by Fenny** [comment]
I'm afraid this is currently not possible to fix with the current design. I added a warning message regarding this issue https://github.com/gofiber/fiber/pull/885/commits/251a2e46e24c6c2148a0770d52e3e385a517bfb5

I'm closing this for now until we make some internal changes, thanks for trying to add unit tests 👍

**Pull request closed without merging**
