### PR TITLE
Expose internal errors.

### PR DESCRIPTION
**Pull request by jorgii**
**Please provide enough information so that others can review your pull request:**

This pull request solves exposes the internal errors so that they can be used publicly.

**Explain the *details* for making this change. What existing problem does the pull request solve?**

The problem is described in https://github.com/gofiber/fiber/issues/1375.

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Review by ReneWerner87 — APPROVED** [review]

**Comment by jorgii** [comment]
This is the easy version of the fix, aliasing the internal errors. This brings the potential problem where someone working on the internal error might not realise that they are exposed to the public.
I am pushing this as a start.
This could be improved by moving all the error definitions outside so that it is explicit they are public.

Does that make sense to do?

**Comment by ReneWerner87** [comment]
yes it makes sense, but because this internal code is a copy, it will be difficult to do so

**Comment by ReneWerner87** [comment]
but when we refresh the code we copied, this customization flies out again, so i think the current solution is good

**Comment by jorgii** [comment]
Alright, making the PR ready for merge.

**Pull request merged**
