### PR TITLE
chore: change interface{} to any

### PR DESCRIPTION
**Pull request by nickajacks1**
## Description

Fix all occurrences of the `use-any` lint issue from `revive` and update the documentation accordingly.

## Changes Introduced

List the new features or adjustments introduced in this pull request. Provide details on benchmarks, documentation updates, changelog entries, and if applicable, the migration guide.  There is no functional change as `any` is an alias of `interface{}`.

- [x] Documentation Update: Detail the updates made to the documentation and links to the changed files.
- [x] API Longevity: Discuss the steps taken to ensure that the new or updated APIs are consistent and not prone to breaking changes.

## Type of Change

Please delete options that are not relevant.

- [x] Enhancement (improvement to existing features and functionality)
- [x] Documentation update (changes to documentation)
- [x] Code consistency (non-breaking change which improves code reliability and robustness)

## Checklist

- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [x] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [x] Ensured that new and existing unit tests pass locally with the changes.

### CODE REVIEW

**Comment by gaby** [comment]
Just to double check, can you run this:

```bash
gofmt -r 'interface{} -> any' -w *.go
```

**Comment by nickajacks1** [comment]
> Just to double check, can you run this:
> 
> ```shell
> gofmt -r 'interface{} -> any' -w *.go
> ```

Cool, didn't know you could do that.
No further change after running `gofmt -r 'interface{} -> any' -w .` and no hits from `grep -Ri 'interface{}'`

**Review by gaby — APPROVED** [review]
LGTM

**Review by efectn — APPROVED** [review]

**Review by sixcolors — APPROVED** [review]
LGTM

**Pull request merged**
