### PR TITLE
:sparkles:feat: add function NewErrors to create multiple new errors

### PR DESCRIPTION
**Pull request by vecpeng**
fix: #1695

### CODE REVIEW

**Comment by ReneWerner87** [comment]
@vecpeng please add a similar documentation 
https://github.com/gofiber/docs/blob/master/api/fiber.md?plain=1#L80-L96
in the docs repository

**Review by ReneWerner87 — APPROVED** [review]

**Comment by vecpeng** [comment]
OK, I will do it soon.

**Comment by balcieren** [comment]
@vecpeng great job 👍

**Comment by balcieren** [comment]
Echo use interface{} for Message.
[Echo HTTPError](https://github.com/labstack/echo/blob/aada6f95d715491107857d3bdf2f7c5c6ba50339/echo.go#L111)
What do you think about it ? @ReneWerner87  @vecpeng

**Pull request merged**
