### PR TITLE
Add test for sendfile in logger

### PR DESCRIPTION
**Pull request by klipitkas**
Adds test for #908 in order to cover regressions.

### CODE REVIEW

**Comment by kiyonlin** [comment]
Hi @klipitkas thanks for the PR. But I don't think it is the right place to put this test case.

**Comment by klipitkas** [comment]
> Hi @klipitkas thanks for the PR. But I don't think it is the right place to put this test case.

Where would the best place be to add this? I think we need to test all cases where bugs have been found but not sure of the proper way to do it. Any help would be appreciated.

**Comment by kiyonlin** [comment]
The bug was found in `Ctx.SendFile`, so it is better to add a test case in `ctx_test.go`.

**Comment by klipitkas** [comment]
> The bug was found in `Ctx.SendFile`, so it is better to add a test case in `ctx_test.go`.

I think this is already covered at https://github.com/gofiber/fiber/blob/master/ctx_test.go#L1306

**Comment by kiyonlin** [comment]
Hey @klipitkas I reviewed the test code and improved it ☝ . Thanks for your PR again!

**Pull request closed without merging**
