### PR TITLE
revert: pr 2286

### PR DESCRIPTION
**Pull request by li-jin-gou**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
Explain the *details* for making this change. What existing problem does the pull request solve?

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by leonklingele** [comment]
Please don't merge yet. I'm about to reply to @gaby's comment.

**Comment by li-jin-gou** [comment]
ok😛



---Original---
From: ***@***.***&gt;
Date: Sun, Jan 29, 2023 18:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gofiber/fiber] revert: pr 2286 (PR #2317)




 
Please don't merge yet. I'm about to reply to @gaby's comment.

**Comment by gaby** [comment]
@li-jin-gou I vote for reopening this, and splitting 2286 into multiple PR's.

**Comment by li-jin-gou** [comment]
> @li-jin-gou I vote for reopening this, and splitting 2286 into multiple PR's.

What others think ？ I'll open it up for now  cc @leonklingele @efectn  @ReneWerner87

**Comment by ReneWerner87** [comment]
i am in contact with leonklingele
would want to avoid a complete revert

leonklingele will add another pull request around the middle of the week, which will handle different tasks

tasks would be:
1. fix for the monitor mw
2. maybe some nolint stuff directly in the yaml and remove the comments
3. error wrapping maybe in a new pr ?
4. change the ChartJsUrl back rename 
5. changes to the internal code copies back

**Comment by li-jin-gou** [comment]
> #2286 i am in contact with leonklingele would want to avoid a complete revert
> 
> leonklingele will add another pull request around the middle of the week, which will handle different tasks
> 
> tasks would be:
> 
> 1. fix for the monitor mw
> 2. maybe some nolint stuff directly in the yaml and remove the comments
> 3. error wrapping maybe in a new pr ?
> 4. change the ChartJsUrl back rename
> 5. changes to the internal code copies back

it is good

**Pull request closed without merging**
