### PR TITLE
add some parameters to config for supporting #1936

### PR DESCRIPTION
**Pull request by taheri24**
Is your feature request related to a problem?
https://github.com/gofiber/fiber/issues/1936  

better implantation  than 
https://github.com/gofiber/fiber/commit/3f3aa7788c6fe8c604de351c1cd682e69d1cc092

### CODE REVIEW

**Comment by efectn** [comment]
nice implementation but `//go:embed` just works on 1.16 and later.

**Comment by taheri24** [comment]
please merge my contribute

**Review by efectn — CHANGES_REQUESTED** [review]
- Add unit test cases (similar: [middleware/monitor/monitor_test.go](https://github.com/gofiber/fiber/blob/3f3aa7788c6fe8c604de351c1cd682e69d1cc092/middleware/monitor/monitor_test.go#L155))
- Add comment lines for new config fields and update README.md.
- Create a PR in docs repo.
- Remove tpl file since we don't need it

**Comment by efectn** [comment]
Check my review @taheri24

**Review by efectn — APPROVED** [review]
lgtm

**Pull request merged**
