### PR TITLE
Fix: logger color output

### PR DESCRIPTION
**Pull request by cloudwindy**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
Explain the *details* for making this change. What existing problem does the pull request solve?

Fixes logger color output

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [X] I tried to make my code as fast as possible with as few allocations as possible
- [X] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
Do not think that this change fixes a problem
Since I can also unfortunately not get any details from the description

**Comment by cloudwindy** [comment]
This fixes the problem that because of the following code, the logger middleware does not show colored output in any cases.
```
if cfg.Output == nil {
	cfg.Output = ConfigDefault.Output
}

// Enable colors if no custom format or output is given
if cfg.Output == nil && checkColorEnable(cfg.Format) {
	cfg.enableColors = true
}
```
Since cfg.Output will be ConfigDefault.Output in case of it is nil, it does not enable colors.

**Comment by ReneWerner87** [comment]
Okay I see, we will see if the output writer is the default one

Can you add a comment for this logic
// check for std streams

**Review by ReneWerner87 — APPROVED** [review]

**Comment by li-jin-gou** [comment]
lgtm

**Pull request merged**
