### PR TITLE
Update startup message formatting

### PR DESCRIPTION
**Pull request by the-hotmann**
## Description

BEFORE:
```
    _______ __             
   / ____(_) /_  ___  _____
  / /_  / / __ \/ _ \/ ___/
 / __/ / / /_/ /  __/ /    
/_/   /_/_.___/\___/_/     v3.0.0-beta.1
--------------------------------------------------
INFO Server started on http://127.0.0.1:8003 (bound on host 0.0.0.0 and port 8003)
INFO Application name: TEST APP
INFO Total handlers count: 5
INFO Prefork: Disabled
INFO PID: 2342
INFO Total process count: 1
20:49:50 | 200 |     593.769µs |   123.123.123.123 | GET     | / 
```

AFTER:
```
    _______ __             
   / ____(_) /_  ___  _____
  / /_  / / __ \/ _ \/ ___/
 / __/ / / /_/ /  __/ /    
/_/   /_/_.___/\___/_/       v3.0.0-beta.1
--------------------------------------------------
INFO Server started on:      http://127.0.0.1:8003 (bound on host 0.0.0.0 and port 8003)
INFO Application name:       TEST APP
INFO Total handlers count:   5
INFO Prefork:                Disabled
INFO PID:                    2342
INFO Total process count:    1

20:49:50 | 200 |     593.769µs |   123.123.123.123 | GET     | /
```

Here some requested screenshots from different shalls (`sh` & `bash` & `dash`):

SH:
image

BASH:
image

DASH:
image

### CODE REVIEW

**Review by gaby — APPROVED** [review]

**Comment by the-hotmann** [comment]
Additional Screenshots with PreFork + Colorless TERM:

SH PreeFork + Colorless (Putty):
image

BASH PreeFork + Colorless (Putty):
image

DASH PreeFork + Colorless (Putty):
image

**Review by ReneWerner87 — APPROVED** [review]

**Comment by gaby** [comment]
@the-hotmann The changes have to be run through https://github.com/mvdan/gofumpt the formatting is making golangci-lint to fail.

**Comment by the-hotmann** [comment]
Should work now.

**Comment by the-hotmann** [comment]
Lol I just called the commit `fix linting #2` which now crossreferenced an issue ..

**Comment by gaby** [comment]
If it fails again run this:

```bash
go install mvdan.cc/gofumpt@latest
gofumpt -l -w listen.go
```

**Comment by gaby** [comment]
> If it fails again run this:
> 
> ```shell
> go install mvdan.cc/gofumpt@latest
> gofumpt -l -w listen.go
> ```

Nvmd, it passed this time :-)

**Comment by the-hotmann** [comment]
@gaby I ran `gofumpt -l -w listen.go` already, it did not change anything. The file was not modified afterwards. Was using `gpfumpt v0.60`.

**Pull request merged**
