### PR TITLE
Reference to issue #1115

### PR DESCRIPTION
**Pull request by xenowits**
**Please provide enough information so that others can review your pull request:**

In response to issue #1115 

**Explain the *details* for making this change. What existing problem does the pull request solve?**

Add response-body and query string params to logger

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Review by ReneWerner87 — APPROVED** [review]

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
@xenowits  please add the new variables to the README.md

**Review by ReneWerner87 — COMMENTED** [review]
@xenowits
could you add your new options also in the gofiber docs repository
https://github.com/gofiber/docs/blob/master/api/middleware/logger.md

**Review by ReneWerner87 — APPROVED** [review]

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
code looks good, but the tests are broken

please check this
image

and don´t forget the markdown files

**Comment by xenowits** [comment]
> code looks good, but the tests are broken
> 
> please check this
> image
> 
> and don´t forget the markdown files

Hi @ReneWerner87 . I have added appropriate tests and added the new logger variables to README. Please let me know if I need to make any more changes. Thanks!

**Comment by xenowits** [comment]
> code looks good, but the tests are broken
> 
> please check this
> image
> 
> and don´t forget the markdown files

Hi @ReneWerner87 . I have added appropriate tests and added the new logger variables to README. Please let me know if I need to make any more changes. Thanks!

**Review by ReneWerner87 — APPROVED** [review]
now the tests look good

but don´t forget the gofiber docs repository

**Comment by xenowits** [comment]
> @xenowits
> now the tests look good
> 
> but don´t forget the gofiber docs repository
> and it would be cool, when you add a separate test for the response body or you extend the Logger_All test(with some output)

Hi @ReneWerner87 . I added new vars to gofiber docs and raised a PR. Also, I created a separate test for the response body.

**Review by ReneWerner87 — COMMENTED** [review]
Think in the response test is still missing a check for the last expected

**Comment by xenowits** [comment]
> Think in the response test is still missing a check for the last expected

Yes @ReneWerner87 . I fixed that mistake! Have a look at the new PR

**Pull request merged**
