### PR TITLE
✨ v3 (enhancement): add `[]byte` support to `utils.EqualFold`

### PR DESCRIPTION
**Pull request by Trim21**
**Please provide enough information so that others can review your pull request:**

replace `utils.EqualFold` signature from `func EqualFold(b, s string) bool` to `func EqualFold[S byteSeq](b, s S) bool`

and add a private interface to utils.

```golang
type byteSeq interface {
	~string | ~[]byte
}
```

**Explain the *details* for making this change. What existing problem does the pull request solve?**

this will make `utils.EqualFold` support comparing bytes like `bytes.EqualFold`

And golang compiler will go monomorphization, which we will have a zero performance cost.

We can also make function like `Trim*` to be generic functions too but I'd like to just change this first for discussion.

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

before:
```text
❯❯ ~\..\..\fiber git:(bind) go test -bench EqualFold -benchmem -run=node .\utils\
goos: windows
goarch: amd64
pkg: github.com/gofiber/fiber/v3/utils
cpu: AMD Ryzen 7 5800X 8-Core Processor
Benchmark_EqualFoldBytes/fiber-16               24507901                48.94 ns/op            0 B/op          0 allocs/op
Benchmark_EqualFoldBytes/default-16              8056410               149.1 ns/op             0 B/op          0 allocs/op
Benchmark_EqualFold/fiber-16                    29971826                39.97 ns/op            0 B/op          0 allocs/op
Benchmark_EqualFold/default-16                   9706066               124.3 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/gofiber/fiber/v3/utils       5.342s
```

after:
```text
❯❯ ~\..\..\fiber git:(bind) go test -bench EqualFold -benchmem -run=node .\utils\
goos: windows
goarch: amd64
pkg: github.com/gofiber/fiber/v3/utils
cpu: AMD Ryzen 7 5800X 8-Core Processor
Benchmark_EqualFoldBytes/fiber-16               24196328                48.71 ns/op            0 B/op          0 allocs/op
Benchmark_EqualFoldBytes/default-16              8000298               149.1 ns/op             0 B/op          0 allocs/op
Benchmark_EqualFold/fiber-16                    29581348                40.24 ns/op            0 B/op          0 allocs/op
Benchmark_EqualFold/default-16                   9373461               124.6 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/gofiber/fiber/v3/utils       5.286s
```

### CODE REVIEW

**Comment by efectn** [comment]
I think it's good idea to use generics for Fiber utils.

**Comment by Trim21** [comment]
I don't why, But I find that using `[]byte` (`BytesEqualFold(b, s []byte) bool`) is even slower than generic `byteSeq`...

```text
goos: windows
goarch: amd64
pkg: github.com/gofiber/fiber/v3/utils
cpu: AMD Ryzen 7 5800X 8-Core Processor
Benchmark_BytesEqualFold
Benchmark_BytesEqualFold/fiber
Benchmark_BytesEqualFold/fiber-16               29250812                40.94 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-16               29241974                40.81 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-16               29241760                40.97 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-16               28878572                40.91 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-bytes-equal-fold
Benchmark_BytesEqualFold/fiber-bytes-equal-fold-16              24204332                49.42 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-bytes-equal-fold-16              23744884                49.71 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-bytes-equal-fold-16              24976584                49.38 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/fiber-bytes-equal-fold-16              23978371                49.14 ns/op            0 B/op          0 allocs/op
Benchmark_BytesEqualFold/default
Benchmark_BytesEqualFold/default-16                              9628075               123.2 ns/op             0 B/op          0 allocs/op
Benchmark_BytesEqualFold/default-16                              9762962               123.7 ns/op             0 B/op          0 allocs/op
Benchmark_BytesEqualFold/default-16                              9604748               123.5 ns/op             0 B/op          0 allocs/op
Benchmark_BytesEqualFold/default-16                              9665220               123.7 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/gofiber/fiber/v3/utils       15.386s
```

**Comment by ReneWerner87** [comment]
by the way i like such changes when the functions can do more and the performance stays the same

now can't we remove the old EqualFold function for bytes ?

we can also try to replace other old functions with many parameters with configuration items instead of 3-4 arguments so that they are extensible

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/v3-beta/utils/bytes.go#L59

**Comment by Trim21** [comment]
Oh, I didn't find there is a `EqualFoldBytes` for bytes... I'll remove it in https://github.com/gofiber/fiber/pull/2030

**Pull request merged**
