### PR TITLE
:sparkles: feature: customizable colors

### PR DESCRIPTION
**Pull request by efectn**
close https://github.com/gofiber/fiber/issues/1890

### CODE REVIEW

**Review by ReneWerner87 — COMMENTED** [review]
Can you pls move all the colors and related stuff in a separate file called "colors.go" to cleanup the app.go a little bit

**Comment by efectn** [comment]
> Can you please put all colors and color related functions in a separate file to keep the app.go clean and small?

Maybe i can create list.go for color and listen related methods. Is it ok to you?

**Comment by ReneWerner87** [comment]
For the colors a color.go and for the listen stuff a listen.go

**Comment by efectn** [comment]
> For the colors a color(s).go or theme.go and for the listen stuff a listen.go

done

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@efectn pls add documentation in the readme and here https://github.com/gofiber/docs/pulls

**Pull request merged**
