### PR TITLE
📝 docs: fix ci badge errors

### PR DESCRIPTION
**Pull request by shuuji3**
## Description

This PR fixes the CI badge errors on `README.md`. This was introduced by the recent update of shields.io. You can read the details here: https://github.com/badges/shields/issues/8671

Fixes # (issue) (skipped as this is a minor change, not a bug of fiber.)

**Before**
Screenshot 2023-01-03 at 2 12 18

**After**
Screenshot 2023-01-03 at 2 11 56

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

This only affects `README.md`.

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.dev/

👌🏻

### CODE REVIEW

**Review by efectn — CHANGES_REQUESTED** [review]
Can you update other READMEs?

**Comment by shuuji3** [comment]
Oh, I missed other translated READMEs. OK, I'll update all of them.

**Comment by shuuji3** [comment]
OK, I've updated all.

**Review by efectn — APPROVED** [review]

**Comment by shuuji3** [comment]
Thanks for merging!

**Pull request merged**
