### PR TITLE
feat: support autocert

### PR DESCRIPTION
**Pull request by mthli**
Golang has a package called [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) which provides automatic access to certificates from Let's Encrypt and any other ACME-based CA. Since [Let’s Encrypt certificates are valid for 90 days](https://letsencrypt.org/2015/11/09/why-90-days.html) , automatic renew certificates is very convenient. 

I want to use autocert with fiber but this issue https://github.com/gofiber/fiber/issues/200 didn't completely solve my problem. So I adapted autocert to fiber by myself, and it works really nice. I think it's time to create a PR to this project.

This sample code shows how this PR works:

```go
package main

import (
	"log"

	"github.com/gofiber/fiber"
	"golang.org/x/crypto/acme/autocert"
)

...

func run(app *fiber.Fiber) {
	// Initialize the autocert.Manager m's Cache, HostPolicy, Prompt, 
	// and other desired options by yourself.
	m := &autocert.Manager{
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist("yourDomain"),
		Cache:      autocert.DirCache("yourCertsDirPath"),
	}

	// Then just call ListenAutoTLS.
	err := app.ListenAutoTLS(443, m)
	if err != nil {
		log.Fatal(err)
	}
}
```

🍻

### CODE REVIEW

**Comment by renanbastos93** [comment]
> Golang has a package called [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) which provides automatic access to certificates from Let's Encrypt and any other ACME-based CA. Since [Let’s Encrypt certificates are valid for 90 days](https://letsencrypt.org/2015/11/09/why-90-days.html) , automatic renew certificates is very convenient.
> 
> I want to use autocert with fiber but this issue #200 didn't completely solve my problem. So I adapted autocert to fiber by myself, and it works really nice. I think it's time to create a PR to this project.
> 
> This sample code shows how this PR works:
> 
> ```go
> package main
> 
> import (
> 	"log"
> 
> 	"github.com/gofiber/fiber"
> 	"golang.org/x/crypto/acme/autocert"
> )
> 
> ...
> 
> func run(app *fiber.Fiber) {
> 	// Initialize the autocert.Manager m's Cache, HostPolicy, Prompt, 
> 	// and other desired options by yourself.
> 	m := &autocert.Manager{
> 		Prompt:     autocert.AcceptTOS,
> 		HostPolicy: autocert.HostWhitelist("yourDomain"),
> 		Cache:      autocert.DirCache("yourCertsDirPath"),
> 	}
> 
> 	// Then just call ListenAutoTLS.
> 	err := app.ListenAutoTLS(443, m)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```
> 
> 🍻

it seems good to me, but I have a question.

Do you want to say that to make renew certs using lib acme, right?

**Comment by mthli** [comment]
Yes, renew certs using lib instead of manual. Another Go web framework [echo](https://echo.labstack.com/) also use [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) to automatic renew certs, see it's doc [Auto TLS Recipe](https://echo.labstack.com/cookbook/auto-tls).

**Comment by renanbastos93** [comment]
> @renanbastos93 Yes, renew certs using lib instead of manual. Another Go web framework called [echo](https://echo.labstack.com/) also use [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) to automatic renew certs, see it's doc [Auto TLS Recipe](https://echo.labstack.com/cookbook/auto-tls).

How nice, I will review your code

**Comment by Fenny** [comment]
@mthli, does this work for you, the best thing would be to add this example to the [recipes](https://github.com/gofiber/recipes) repo.
```go
package main

import (
    "crypto/tls"

    "github.com/gofiber/fiber"
    "golang.org/x/crypto/acme/autocert"
)

func main() {
    app := fiber.New()

    app.Get("/", func(c *fiber.Ctx) {
        c.Send("Hi TLS")
    })

    m := &autocert.Manager{
        Prompt:     autocert.AcceptTOS,
        HostPolicy: autocert.HostWhitelist("example.com"),
        Cache:      autocert.DirCache("./certs"),
    }

    tls := &tls.Config{
        GetCertificate: m.GetCertificate,
    }

    app.Listen(443, tls)
}
```

**Comment by mthli** [comment]
@Fenny the following code will work:

```go
package main

import (
	"crypto/tls"
	"log"

	"github.com/gofiber/fiber"
	"golang.org/x/crypto/acme"
	"golang.org/x/crypto/acme/autocert"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) {
		c.Send("Hi TLS")
	})

	m := &autocert.Manager{
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist("example.com"), // replaced with your domain
		Cache:      autocert.DirCache("./certs"),
	}

	tls := &tls.Config{
		GetCertificate: m.GetCertificate,
		// Must add acme.ALPNProto to NextProtos for TLS-ALPN-01.
		// Or just use m.TLSConfig() and remove it's NextProtos "h2" string.
		NextProtos: []string{
			"http/1.1", acme.ALPNProto,
		},
	}

	err := app.Listen(443, tls)
	if err != nil {
		log.Fatal(err)
	}
}
```

Since [Let’s Encrypt has rate limits](https://letsencrypt.org/docs/rate-limits/), it's recommended to use it's staging environment to test the code, see the doc [Staging Environment](https://letsencrypt.org/docs/staging-environment/). Here are some brief test steps:

1. Open the package source code `autocert.go` , change `DefaultACMEDirectory` value to `https://acme-staging-v02.api.letsencrypt.org/directory` and save.
2. Exec `go build -a` to force rebuilding all packages in your VPS.
3. Download the staging environment intermediate certificate from [the doc](https://letsencrypt.org/docs/staging-environment/#root-certificate) to your computer, add it to your computer trust store.
4. Open a browser to visit your domain, you will see `Hi LTS` string.

Also, move to the recipes repo should be a better choice 😄

**Comment by Fenny** [comment]
@mthli Awesome, I added it to the recipes :-)
https://github.com/gofiber/recipes/blob/master/autocert/main.go

**Pull request closed without merging**
