### PR TITLE
Use colorable for Windows

### PR DESCRIPTION
**Pull request by mattn**
image

### CODE REVIEW

**Comment by Fenny** [comment]
@mattn, nice catch thanks!

**Comment by koddr** [comment]
@Fenny it's okay, but it adds another addiction that I don't think is necessary at all. 

Does we really need to enter an extra package so that on Windows one line is not colored white? IMHO, absolutely not. **Fiber** is minimalism. I understand, why we use `jsontier` — it's fastest package than `encode/json`, but this... uh?

> And, btw, what is this console? CMD? PowerShell?

**Comment by mattn** [comment]
I use cmd.exe. I don't mind you revert this and remove escape sequences.

**Comment by keob** [comment]
@mattn You can try use powershell core，looks great😀

**Comment by mattn** [comment]
Since powershell is too heavy to start-up, I don't use it.

FYI, Well, this issue will not be resolved eventhough you use powershell or powershell core. If you want to solve this, the console must be set ENABLE_VIRTUAL_TERMINAL_PROCESSING using API.

See https://docs.microsoft.com/en-us/windows/console/setconsolemode?redirectedfrom=MSDN#ENABLE_VIRTUAL_TERMINAL_PROCESSING

**Comment by mattn** [comment]
image

**Comment by keob** [comment]
@mattn 😅😅, thanks😀

**Pull request merged**
