### PR TITLE
:sparkles:feat: add retryIf function to client agent

### PR DESCRIPTION
**Pull request by vecpeng**
RetryIf function for client agent.
```go
func (a *Agent) RetryIf(retryIf RetryIfFunc) *Agent {
	a.HostClient.RetryIf = retryIf
	return a
}
```
Examples:
```go
agent.Get("https://example.com").RetryIf(func (req *fiber.Request) bool {
	return req.URI() == "https://example.com"
}
```

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Thx, don't forget the doc repository.

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@vecpeng
Don't forget the documentation repository
https://github.com/gofiber/docs

**Comment by ReneWerner87** [comment]
@vecpeng can you create another pull request for the documentation repository?

**Comment by tomaswarynyca** [comment]
It seems to me that it is already done
https://github.com/gofiber/docs/pull/230

**Comment by ReneWerner87** [comment]
Oh thx

**Pull request merged**
