### PR TITLE
Add route naming feature.

### PR DESCRIPTION
**Pull request by efectn**
Set route name by last created route or group.

**Example Use:**

_Code:_
```go
func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error { 
		...
	})
	app.Name("index")

	app.Get("/doe", func(c *fiber.Ctx) error { 
		...
	}).Name("homgfgfe")

	app.Trace("/tracer", func(c *fiber.Ctx) error {
		...
	}).Name("tracert")

	app.Delete("/delete", func(c *fiber.Ctx) error {
		...
	}).Name("delete")

	a := app.Group("/a")
	a.Name("fd.")

	a.Get("/test", func(c *fiber.Ctx) error {
		...
	}).Name("test")

	data, _ := json.MarshalIndent(app.Stack(), "", "  ")
	fmt.Print(string(data))

	app.Listen("localhost:8080")

}
```

_Output:_
```
[
  [
    {
      "method": "GET",
      "name": "index",
      "path": "/",
      "params": null
    },
    {
      "method": "GET",
      "name": "homgfgfe",
      "path": "/doe",
      "params": null
    },
    {
      "method": "GET",
      "name": "fd.test",
      "path": "/a/test",
      "params": null
    }
  ],
  [
    {
      "method": "HEAD",
      "name": "",
      "path": "/",
      "params": null
    },
    {
      "method": "HEAD",
      "name": "",
      "path": "/doe",
      "params": null
    },
    {
      "method": "HEAD",
      "name": "",
      "path": "/a/test",
      "params": null
    }
  ],
  null,
  null,
  [
    {
      "method": "DELETE",
      "name": "delete",
      "path": "/delete",
      "params": null
    }
  ],
  null,
  null,
  [
    {
      "method": "TRACE",
      "name": "tracert",
      "path": "/tracer",
      "params": null
    }
  ],
  null
]
```

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Interesting

Can you check the tests, the last run is not successful

**Comment by efectn** [comment]
@ReneWerner87 do you know why parallel tests cause errors?

**Comment by hi019** [comment]
Instead of .RouteName, I think .Name would suffice

**Comment by efectn** [comment]
> Instead of .RouteName, I think .Name would suffice

Right. I'll change it today

**Comment by efectn** [comment]
> Interesting
> 
> Can you check the tests, the last run is not successful

fixed

**Comment by ReneWerner87** [comment]
its looking good, can you add some documentation in the readme and doc repository

**Comment by efectn** [comment]
> its looking good, can you add some documentation in the readme and doc repository

What should i add in README? As feature?

**Comment by ReneWerner87** [comment]
Yes please

**Comment by balcieren** [comment]
@efectn will it work like 
```go
func main() {
	app := fiber.New()

        app.Get("/user",func(c *fiber.Ctx) error {...}).Name("user").Get("/projects",func(c *fiber.Ctx)error {...}).Name("projects")

	app.Listen("localhost:8080")
}
```

**Comment by efectn** [comment]
> @efectn will it work like
> 
> ```go
> func main() {
> 	app := fiber.New()
> 
>         app.Get("/user",func(c *fiber.Ctx) error {...}).Name("user").Get("/projects",func(c *fiber.Ctx)error {...}).Name("projects")
> 
> 	app.Listen("localhost:8080")
> }
> ```

Yeah it will work

**Comment by balcieren** [comment]
> > @efectn will it work like
> > ```go
> > func main() {
> > 	app := fiber.New()
> > 
> >         app.Get("/user",func(c *fiber.Ctx) error {...}).Name("user").Get("/projects",func(c *fiber.Ctx)error {...}).Name("projects")
> > 
> > 	app.Listen("localhost:8080")
> > }
> > ```
> 
> Yeah it will work

👍

**Pull request merged**
