### PR TITLE
♻️ v3: fix!: ContextKey collisions

### PR DESCRIPTION
**Pull request by sixcolors**
## Description

Fixes context key collision issues in middleware and `ctx.go`. Follows best practice/convention from [context](https://pkg.go.dev/context) by using unexported key types to avoid collisions.

Related to #2684 which outlines the issue and rationale for change.

## Changes Introduced

List the new features or adjustments introduced in this pull request. Provide details on benchmarks, documentation updates, changelog entries, and if applicable, the migration guide.

- [x] Documentation Update: Detail the updates made to the documentation and links to the changed files.
- [x] Changelog/What's New: Include a summary of the additions for the upcoming release notes.
- [ ] Migration Guide: If necessary, provide a guide or steps for users to migrate their existing code to accommodate these changes.
- [x] API Longevity: Discuss the steps taken to ensure that the new or updated APIs are consistent and not prone to breaking changes.
- [x] Examples: Provide examples demonstrating the new features or changes in action.

## Type of Change

Please delete options that are not relevant.

- [x] Enhancement (improvement to existing features and functionality)
- [x] Documentation update (changes to documentation)
- [x] Code consistency (breaking change which improves code reliability and robustness)
- [x] Breaking change

## Checklist

Before you submit your pull request, please make sure you meet these requirements:

- [x] Followed the inspiration of the Express.js framework for new functionalities, making them similar in usage.
- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [x] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [x] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [x] Ensured that new and existing unit tests pass locally with the changes.
- [x] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.
- [x] Aimed for optimal performance with minimal allocations in the new code.

## Commit Formatting

Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.md#pull-requests-or-commits)

### CODE REVIEW

**Comment by sixcolors** [comment]
fixed to contrib packages: https://github.com/gofiber/contrib/pull/896

**Comment by sixcolors** [comment]
@benjajaja tag

**Comment by sixcolors** [comment]
@ReneWerner87 I didn't see a v3 branch in the repo, please let me know how you want to handle this for contrib.

**Comment by ReneWerner87** [comment]
> @ReneWerner87 I didn't see a v3 branch in the repo, please let me know how you want to handle this for contrib.

we haven't created one there yet, but you are welcome to create a beta branch

**Comment by ReneWerner87** [comment]
with this concept it is no longer possible to customize the context key from the outside

does this have any disadvantages for us? @gofiber/maintainers @gofiber/contributors 
i only have one usecase in mind where you use the middlewares multiple times, but that would only lead to problems with the same routes, but where you don't use these special ones twice or ?
does anyone have any worst cases in mind ?

otherwise the code looks well implemented according to this concept

**Review by ReneWerner87 — APPROVED** [review]

**Review by renanbastos93 — APPROVED** [review]
Awesome, you did a good job!

**Comment by efectn** [comment]
> with this concept it is no longer possible to customize the context key from the outside
> 
> does this have any disadvantages for us? @gofiber/maintainers @gofiber/contributors i only have one usecase in mind where you use the middlewares multiple times, but that would only lead to problems with the same routes, but where you don't use these special ones twice or ? does anyone have any worst cases in mind ?
> 
> otherwise the code looks well implemented according to this concept

I am happy with change since it's recommended behavior by Go context docs.

**Review by efectn — APPROVED** [review]

**Review by gaby — APPROVED** [review]

**Comment by sixcolors** [comment]
> with this concept it is no longer possible to customize the context key from the outside
> 
> does this have any disadvantages for us? @gofiber/maintainers @gofiber/contributors i only have one usecase in mind where you use the middlewares multiple times, but that would only lead to problems with the same routes, but where you don't use these special ones twice or ? does anyone have any worst cases in mind ?
> 
> otherwise the code looks well implemented according to this concept

I didn’t envision anyone using the same middleware twice with the same routes.

the package function improves the developer experience and makes the framework more approachable IMO. Also some existing middleware already use this approach with predicate functions, they were just using constant strings before.

**Comment by ReneWerner87** [comment]
Currently this should work, just wanted to mention it
Already had 1 or 2 reports where people wanted to use the limiter middleware multiple times for the same route with different settings, which also made sense because these then ensured with the internal next that they were not both executed
But the code should work. As long as no one else has something in mind that speaks against it

**Comment by GalvinGao** [comment]
A pretty minor point here, but you could use `var contextKey struct{}` to achieve zero memory allocation during initialization and still able to ensure type safety.

**Comment by sixcolors** [comment]
> A pretty minor point here, but you could use `var contextKey struct{}` to achieve zero memory allocation during initialization and still able to ensure type safety.

Where there are multiple keys it would wind up something like this:

```go
type contextKeyToken struct{}
type contextKeyPayload struct{}

const (
    tokenKey contextKeyToken = struct{}{}
    payloadKey contextKeyPayload = struct{}{}
)
```

vs

```go
type contextKey int

 const (
 	usernameKey contextKey = iota
 	passwordKey
 )
 ```
 
I prefered the style of iota when multiple context keys were used in a packageand the [context](https://pkg.go.dev/context#Context) package used a `type key int` in it's example.
 
However, what does everyone else prefer? Do you find the distinct struct types or iota style more readable and maintainable.

**Comment by sixcolors** [comment]
> A pretty minor point here, but you could use `var contextKey struct{}` to achieve zero memory allocation during initialization and still able to ensure type safety.

Where there are multiple keys it would wind up something like this:

```go
type (
	contextKeyUsername struct{}
	contextKeyPassword struct{}
)

var (
	usernameKey contextKeyUsername
	passwordKey contextKeyPassword
)
```

In the above code, two key variables are stored on the stack, and they point to an instance of contextKey*. Because contextKey* is an empty struct, it does not take up any memory, and there are no heap allocations. However, the variable keys take up a small amount of stack space (the size of a pointer).

vs

```go
type contextKey int

 const (
 	usernameKey contextKey = iota
 	passwordKey
 )
 ```

This approach does not cause any heap allocations or take up any runtime stack space because constants in Go are replaced by their values at compile time where they are used.

So, AFAIK both approaches would ensure type safety and uniqueness of keys. And have zero allocs on the heap.

---
 
I preferred the style of iota when multiple context keys were used, also stand lib [context](https://pkg.go.dev/context#Context) package uses a `type key int` in its example.
 
However, what does everyone else prefer? Do you find the distinct struct types or iota style more readable and maintainable?

**Comment by ReneWerner87** [comment]
Since the allocations are at the registration time it doesn't matter for me

**Comment by sixcolors** [comment]
> Since the allocations are at the registration time it doesn't matter for me
> 
> But i prefer the iota variant

From what I understand, in Go, constants are not allocated in memory like variables are. Instead, they are replaced by their values at compile time and do not have an address. This implies that constants do not exist while the program is running and there is no memory allocation for them other than the executable program code. Therefore, using const with iota would appear to be a zero allocation solution.

However, please let me know if I've misunderstood anything.

**Pull request merged**
