### PR TITLE
Cookie parser

### PR DESCRIPTION
**Pull request by joey1123455**
## Description

Implemented a cookie parser, following the same convention used by BodyParser and QuerryParser context methods.
The parser is a context method which takes a struct pointer as argument and assigns all passed cookies to the relevant fields. It returns an error if any.

The feature was requested as an issue, and provides an easier way to handle multiple cookies, and improves developer experience and development time.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:

- [X] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [X] I tried to make my code as fast as possible with as few allocations as possible
- [X] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by joey1123455** [comment]
the issue for this pull request is 
🚀 [Feature]: CookieParser #2639
https://github.com/gofiber/fiber/issues/2639#issue-1902683846

**Comment by joey1123455** [comment]
@ReneWerner87 Hello, I would like to know what needs to be done before a PR is approved.

**Comment by ReneWerner87** [comment]
Currently everything we need is there
However, we are still discussing internally and since it is vacation time it is currently a bit slower

**Review by ReneWerner87 — APPROVED** [review]

**Comment by joey1123455** [comment]
@ReneWerner87 hello Rene, I noticed some checks failed. Is there anything I need to do?

**Comment by ReneWerner87** [comment]
Yes, pls check the lint errors

**Comment by ReneWerner87** [comment]
image

**Comment by joey1123455** [comment]
I'll fix all the issues tonight

**Comment by joey1123455** [comment]
Sorry for disturbing you, but I'm trying to confirm the last error I just need to add a test for the returned value? @ReneWerner87

**Comment by ReneWerner87** [comment]
> Sorry for disturbing you, but I'm trying to confirm the last error I just need to add a test for the returned value? @ReneWerner87

yes should be
but would recommend you to watch the binary locally via act or direct

https://github.com/nektos/act
```go
act -W ./.github/workflows/linter.yml
```

**Comment by joey1123455** [comment]
> > Sorry for disturbing you, but I'm trying to confirm the last error I just need to add a test for the returned value? @ReneWerner87
> 
> yes should be but would recommend you to watch the binary locally via act or direct
> 
> https://github.com/nektos/act
> 
> ```shell
> act -W ./.github/workflows/linter.yml
> ```

code
this is the test i wrote for it and i have other tests for the return value as well
code3
code1

**Comment by ReneWerner87** [comment]
image

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/2656/commits/bb026a6044d94633bafd91973e14a8e54baf389d fixed

**Pull request merged**
