### PR TITLE
feat: Migrate monitor middleware from Fiber v2 to v3

### PR DESCRIPTION
**Pull request by Redish101**
# Description

Migrate monitor middleware from fiber v2 to v3.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

Before you submit your pull request, please make sure you meet these requirements:

- [x] Followed the inspiration of the Express.js framework for new functionalities, making them similar in usage.
- [x] Conducted a self-review of the code and provided comments for complex or critical parts.
- [x] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
- [x] Added or updated unit tests to validate the effectiveness of the changes or new features.
- [x] Ensured that new and existing unit tests pass locally with the changes.
- [x] Verified that any new dependencies are essential and have been agreed upon by the maintainers/community.
- [x] Aimed for optimal performance with minimal allocations in the new code.
- [x] Provided benchmarks for the new code to analyze and improve upon.

### CODE REVIEW

**Comment by gaby** [comment]
@Redish101 The monitor middleware was removed from v3 on purpose. The end goal is to migrate it to the gofiber/contrib repo.

**Comment by Redish101** [comment]
> @Redish101 The monitor middleware was removed from v3 on purpose. The end goal is to migrate it to the gofiber/contrib repo.

Well, I will move these changes to gofiber/contrib repo.

**Comment by gaby** [comment]
> > @Redish101 The monitor middleware was removed from v3 on purpose. The end goal is to migrate it to the gofiber/contrib repo.
> 
> Well, I will move these changes to gofiber/contrib repo.

Thanks, one thing. You have to fix the gopsutil version, it should be this one https://github.com/shirou/gopsutil/releases/tag/v4.24.8 in the `go.mod`

**Comment by Redish101** [comment]
> > > @Redish101 The monitor middleware was removed from v3 on purpose. The end goal is to migrate it to the gofiber/contrib repo.
> > 
> > 
> > Well, I will move these changes to gofiber/contrib repo.
> 
> Thanks, one thing. You have to fix the gopsutil version, it should be this one https://github.com/shirou/gopsutil/releases/tag/v4.24.8 in the `go.mod`

I have moved these changes to [gofiber/contrib#1171](https://github.com/gofiber/contrib/pull/1171) and updated gopsutils to v4.24.8.

**Pull request closed without merging**
