### PR TITLE
v3(tests): use testify for assertion

### LINKED ISSUE #2035: 🚀 v3 Request: use https://github.com/stretchr/testify for testing
### Feature Description

remove current `utils.AssertEqual` and use https://github.com/stretchr/testify for testing assertion

### Additional Context (optional)

_No response_

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

### PR DESCRIPTION
**Pull request by Trim21**
**Please provide enough information so that others can review your pull request:**
close #2035

**Explain the *details* for making this change. What existing problem does the pull request solve?**

replace all `utils.AssertEqual` with `testify/require`

### CODE REVIEW

**Comment by Trim21** [comment]
I'm not very familiar with our PR merging workflow, can I just merge it or I should wait another maintainer to do it 🤔

**Comment by ReneWerner87** [comment]
Just wait for the maintainers. You can merge little things like dependencies updates, documentation or test update, but should wait for big decisions.

**Comment by ReneWerner87** [comment]
And best never merge your own code without feedback from others, otherwise no one can give feedback.

**Comment by efectn** [comment]
Testify is OK to me since it has more detailed output and better methods.

**Comment by ReneWerner87** [comment]
Just don't know if we should do that
The idea of fenny then, was to have as little dependence as possible

Hope in version 3 we can follow this idea as good as possible, so if it is not absolutely necessary, we should not make ourselves dependent

**Comment by efectn** [comment]
I think v3 has less deps than v2 at the moment. We can also write custom extractor instead of using `msgp` i suppose.

https://github.com/gofiber/fiber/blob/v3-beta/go.mod

**Comment by Trim21** [comment]
I want say that vendoring go package in `internal/` is not a good idea .....

**Comment by ReneWerner87** [comment]
Yes I agree, that's why I have already allowed some dependencies

My only question is if we got along with our native test functions so far, do we really need an extra package?
Should only be questioned so we have as few dependencies as possible

**Comment by Trim21** [comment]
that dependent on why we need to "have as little dependence as possible" I think 🤔

To make user download less code or something else?

**Comment by ReneWerner87** [comment]
One dependency quickly becomes several, when the next developer wants to write his test with other libs we suddenly have a lot of dependencies.

But if we don't allow these from the beginning and extend our internal test function a bit, we would be free from these decisions.

I'll look at the code later which assertion is not possible with our internal function

**Comment by Trim21** [comment]
> when the next developer wants to write his test with other libs we suddenly have a lot of dependencies.

I think we can have some code style guide about this...

**Pull request merged**
