### PR TITLE
📝docs(middleware): fix alignment in limiter example

### PR DESCRIPTION
**Pull request by TwiN**
Noticed a small alignment issue while going through the docs.

### CODE REVIEW

**Comment by gaby** [comment]
@TwiN the docs for the website are hosted here: https://github.com/gofiber/docs

**Comment by TwiN** [comment]
@gaby I'm aware, I just happened to stumble upon the README while going through the code.

If it's a non-issue because all users are expected to go strictly through the docs website, feel free to close the PR :)

**Review by gaby — APPROVED** [review]

**Comment by leonklingele** [comment]
This is not how Go indents. go fmt would spit out:

```go
    Max:          20,
    Expiration:   30 * time.Second,
    KeyGenerator: func(c *fiber.Ctx) string{
```

**Comment by TwiN** [comment]
@leonklingele Did you try it? :P 

go fmt breaks alignment when a parameter is defined with more than one line.

Here's an example:
```go
package main

type T struct {
	Age       int
	SomeSlice []string
	FirstName string
	LastName  string
}

func main() {
	// If all parameters are defined on their respective line, they will all be aligned
	_ = T{
		Age:       123,
		SomeSlice: []string{"hello", "world"},
		FirstName: "John",
		LastName:  "Doe",
	}
	// If a parameter with a new line is present, the algorithm doesn't align it with the previous and next fields/parameters
	_ = T{
		Age: 123,
		SomeSlice: []string{
			"hello",
			"world",
		},
		FirstName: "John",
		LastName:  "Doe",
	}
}
```

If you don't believe me, feel free to try it on https://go.dev/play/

See https://github.com/golang/go/issues/31431 for more details on the reason why

**Comment by li-jin-gou** [comment]
same to https://github.com/gofiber/docs/blob/master/api/middleware/limiter.md  @TwiN

**Review by li-jin-gou — APPROVED** [review]
LGTM

**Pull request merged**
