### PR TITLE
🔥 Add Global ViewLayout

### PR DESCRIPTION
**Pull request by sujit-baniya**
**Please provide enough information so that others can review your pull request:**
This PR will resolve https://github.com/gofiber/fiber/issues/1382 by adding `ViewLayout` in fiber.Config allowing users to not define layout everywhere
**Explain the *details* for making this change. What existing problem does the pull request solve?**
This change allows user pass layout as global config and User don't need to pass layout on each render

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Thanks, can you please leave another description in the readme or in the docs repository

**Comment by sujit-baniya** [comment]
@ReneWerner87  Added description on docs: https://github.com/gofiber/docs/pull/179

**Comment by ReneWerner87** [comment]
thx, mist forgot to mention the first time, can you please add another testcase

**Comment by ReneWerner87** [comment]
something like this
https://github.com/gofiber/fiber/blob/master/ctx_test.go#L1651-L1663

**Comment by sujit-baniya** [comment]
@ReneWerner87 It seems need to add most of the functionality for template to be added. Will it be acceptable if I add test template engine similar to html template for test?

**Comment by ReneWerner87** [comment]
use the template test engine as in the other tests

**Comment by sujit-baniya** [comment]
@ReneWerner87  Added test case for Views Layout

**Review by ReneWerner87 — COMMENTED** [review]
thx

**Pull request merged**
