### PR TITLE
Replaced double quotes with backticks in all route parameter strings 

### PR DESCRIPTION
**Pull request by 11-aryan**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
Explain the *details* for making this change. What existing problem does the pull request solve?

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

### CODE REVIEW

**Comment by Skyenought** [comment]
@11-aryan Why not use double quotes? Please give a reason

**Comment by 11-aryan** [comment]
@Skyenought As pjebs nebe had mentioned in the issue description, in go's regex documentation, they always use backticks to make sure it is unambiguous and the escape character doesn't interfere with regex patterns in an unexpected way.

**Comment by ReneWerner87** [comment]
understandable, but please only where escaped, the normal case should already be the double quote


from issue report:
image

currently im PR
image

can we also adjust the test which is in the code with the backticks to make sure that works what we mention in the docs

**Comment by 11-aryan** [comment]
Yeah sure, I'll change it

**Comment by ReneWerner87** [comment]
@11-aryan any progress ?

**Comment by 11-aryan** [comment]
@ReneWerner87 I'm looking into it.

**Comment by 11-aryan** [comment]
@ReneWerner87 I've made the required changes.

**Comment by ReneWerner87** [comment]
Ok. Thanks

**Review by ReneWerner87 — APPROVED** [review]

**Review by gaby — APPROVED** [review]

**Pull request merged**
